import {categories,modes,milestones,boosters,sentences} from './src/data/content.js';
import {getState,patch,update,level,levelXp,xpToNext,addReward,buy,markLearned} from './src/core/store.js';

const app=document.querySelector('#app');
let game={mode:null,items:[],step:0,score:0,combo:0,current:null,selected:[],bank:[],memory:[],open:[],matched:[],timer:null,time:45};
const s=()=>getState();
const tr=(de,es)=>s().lang==='de'?de:es;
const target=()=>s().lang==='de'?'es':'de';
const category=()=>categories.find(c=>c.id===s().category)||categories[0];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const availableWords=c=>c.words.slice(0,Math.min(c.words.length,8+Number((s().learned[`pack-${c.id}`]||0))*4));

function speak(text,lang=target()){
 if(!s().sound||!('speechSynthesis'in window))return;
 speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='de'?'de-DE':'es-ES';u.rate=.8;u.pitch=1.02;speechSynthesis.speak(u)
}
function clearTimer(){if(game.timer){clearInterval(game.timer);game.timer=null}}
function shell(){return `<span class="shell">🐚 <b>${s().shells}</b></span>`}
function header(back=false){return `<header class="topbar">${back?'<button class="circle" data-action="back">←</button>':'<button class="circle" data-action="settings">☰</button>'}<div class="brand"><span>🐢</span><b>LinguaTurtle</b></div>${shell()}</header>`}
function nav(active){return `<nav class="bottom-nav">${[['home','⌂','Home'],['worlds','◉',tr('Lernwelten','Mundos')],['library','▤',tr('Bibliothek','Biblioteca')],['shop','♧',tr('Boutique','Boutique')],['profile','♙',tr('Profil','Perfil')]].map(x=>`<button class="${active===x[0]?'active':''}" data-screen="${x[0]}"><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</nav>`}
function levelBar(){return `<section class="level-panel"><div class="level-head"><div><span>${tr('Lernstufe','Nivel')} ${level()}</span><strong>${s().xp} XP</strong></div><b>${tr(`Noch ${xpToNext()} XP bis Stufe ${level()+1}`,`Faltan ${xpToNext()} XP para nivel ${level()+1}`)}</b></div><div class="progress"><i style="width:${levelXp()}%"></i></div></section>`}
function daily(){const n=Math.min(5,s().dailyCount||0);return `<section class="daily"><div><span>🔥</span><div><strong>${tr('Tagesziel','Meta diaria')}</strong><small>${n}/5 ${tr('Übungen','ejercicios')}</small></div></div><div class="dots">${[0,1,2,3,4].map(i=>`<i class="${i<n?'on':''}"></i>`).join('')}</div></section>`}
function render(){clearTimer();const screen=s().screen||'home';({home:renderHome,worlds:renderWorlds,library:renderLibrary,shop:renderShop,profile:renderProfile,category:renderCategory,game:renderGame,sentence:renderSentence,memory:renderMemory,speed:renderSpeed,complete:renderComplete}[screen]||renderHome)()}

function renderHome(){patch({screen:'home'});app.innerHTML=`${header()}<section class="hero"><div class="hero-copy"><span class="eyebrow">KALOS ÓRITES</span><h1>${tr('Willkommen zurück!','¡Bienvenido de nuevo!')}</h1><p>${tr('Tula freut sich, heute mit dir zu lernen.','Tula está feliz de aprender contigo.')}</p></div><div class="tula-portrait"><span>🐢</span></div></section>${levelBar()}<section class="stats"><div><span>⭐</span><strong>${s().xp}</strong><small>XP</small></div><div><span>🐚</span><strong>${s().shells}</strong><small>${tr('Muscheln','Conchas')}</small></div><div><span>🔥</span><strong>${s().streak}</strong><small>${tr('Lerntage','Días')}</small></div></section>${daily()}<section class="section-head"><div><span class="eyebrow">${tr('DEINE REISE','TU VIAJE')}</span><h2>${tr('Heute weiterlernen','Continuar hoy')}</h2></div></section><button class="featured" data-open-category="${s().category}"><span>${category().icon}</span><div><small>${tr('Ausgewählte Lernwelt','Mundo elegido')}</small><strong>${category()[s().lang]}</strong><em>${availableWords(category()).length} ${tr('Wörter im Pool','palabras')}</em></div><b>→</b></button><section class="quick-grid"><button data-screen="library"><span>📚</span><strong>${tr('Wörterbibliothek','Biblioteca')}</strong><small>${Object.keys(s().learned).filter(k=>!k.startsWith('pack-')).length} ${tr('gelernt','aprendidas')}</small></button><button data-screen="shop"><span>♛</span><strong>${tr('Muschel-Boutique','Boutique')}</strong><small>${tr('Modi & Booster','Modos y mejoras')}</small></button></section>${nav('home')}`}

function renderWorlds(){patch({screen:'worlds'});app.innerHTML=`${header()}<section class="page-title"><span class="eyebrow">${tr('LERNWELTEN','MUNDOS')}</span><h1>${tr('Entdecke neue Räume','Descubre nuevas salas')}</h1><p>${tr('Jede Welt wächst mit deinem Wortschatz.','Cada mundo crece con tu vocabulario.')}</p></section><div class="world-grid">${categories.map((c,i)=>`<button data-open-category="${c.id}"><span class="world-no">${String(i+1).padStart(2,'0')}</span><span class="world-icon">${c.icon}</span><div><strong>${c[s().lang]}</strong><small>${availableWords(c).length}/${c.words.length} ${tr('Wörter verfügbar','palabras disponibles')}</small><div class="mini-progress"><i style="width:${availableWords(c).length/c.words.length*100}%"></i></div></div><b>→</b></button>`).join('')}</div>${nav('worlds')}`}

function renderLibrary(){patch({screen:'library'});const learnedIds=Object.keys(s().learned).filter(k=>!k.startsWith('pack-'));app.innerHTML=`${header()}<section class="page-title"><span class="eyebrow">${tr('WÖRTERBIBLIOTHEK','BIBLIOTECA')}</span><h1>${tr('Dein wachsender Wortschatz','Tu vocabulario creciente')}</h1><p>${tr('Neue Wörterpakete vergrößern deinen Lernpool dauerhaft.','Los paquetes amplían tu grupo de palabras.')}</p></section><section class="library-progress"><div><strong>${learnedIds.length} / ${categories.reduce((n,c)=>n+c.words.length,0)}</strong><small>${tr('Wörter bereits geübt','palabras practicadas')}</small></div><div class="progress"><i style="width:${Math.min(100,learnedIds.length/1.08)}%"></i></div></section><div class="library-sections">${categories.map(c=>{const words=availableWords(c);const more=words.length<c.words.length;return `<section class="library-category"><header><div><span>${c.icon}</span><div><strong>${c[s().lang]}</strong><small>${words.length}/${c.words.length}</small></div></div>${more?`<button data-pack="${c.id}">+4 · 🐚 50</button>`:'<em>✓ Komplett</em>'}</header><div class="word-grid">${words.map(w=>`<article class="${s().learned[w.id]?'learned':''}"><span>${w.emoji}</span><strong>${w[s().lang]}</strong><small>${w[target()]}</small></article>`).join('')}</div></section>`}).join('')}</div>${nav('library')}`}

function renderShop(){patch({screen:'shop'});app.innerHTML=`${header()}<section class="page-title"><span class="eyebrow">${tr('MUSCHEL-BOUTIQUE','BOUTIQUE')}</span><h1>${tr('Modi und Booster','Modos y mejoras')}</h1><p>${tr('Alles wird erspielt. Es gibt keine echten Käufe.','Todo se gana jugando. No hay compras reales.')}</p></section><div class="shop-tabs"><span class="active">${tr('Modi','Modos')}</span><span>Booster</span><span>${tr('Wörter','Palabras')}</span></div><div class="shop-list">${modes.filter(m=>!m.free).map(m=>{const owned=s().unlocked.includes(m.id);return `<article><span>${m.icon}</span><div><strong>${m[s().lang]}</strong><small>${owned?tr('Freigeschaltet','Desbloqueado'):tr('Neuer Spielmodus','Nuevo modo')}</small></div><button data-buy-mode="${m.id}" ${owned?'disabled':''}>${owned?'✓':`🐚 ${m.cost}`}</button></article>`}).join('')}<h3>Booster</h3>${boosters.map(b=>`<article><span>${b.icon}</span><div><strong>${b[s().lang]}</strong><small>${b.id==='jump'?`${s().boosters.jumps||0} ${tr('gespeichert','guardados')}`:tr('Einmalig aktivieren','Activar')}</small></div><button data-buy-booster="${b.id}">🐚 ${b.cost}</button></article>`).join('')}</div>${nav('shop')}`}

function renderProfile(){patch({screen:'profile'});app.innerHTML=`${header()}<section class="profile-hero"><div class="avatar">🐢</div><span class="eyebrow">${tr('DEIN FORTSCHRITT','TU PROGRESO')}</span><h1>${tr('Lernstufe','Nivel')} ${level()}</h1><strong>${s().xp} XP</strong>${levelBar()}</section>${daily()}<section class="streak"><h2>${tr('Lernserie','Racha')}</h2><div>${['Mo','Di','Mi','Do','Fr','Sa','So'].map((d,i)=>`<span class="${i<Math.min(7,s().streak)?'on':''}"><i></i>${d}</span>`).join('')}</div></section><section class="milestones"><h2>${tr('Level-Belohnungen','Recompensas')}</h2>${milestones.map(m=>{const reached=level()>=m.level,claimed=s().claimed.includes(m.level);return `<article class="${reached?'reached':''}"><span>${m.icon}</span><div><small>LEVEL ${m.level}</small><strong>${m[s().lang]}</strong><em>${m.detail}</em></div>${reached&&!claimed?`<button data-claim="${m.level}">${tr('Abholen','Recoger')}</button>`:claimed?'<b>✓</b>':'<b>🔒</b>'}</article>`}).join('')}</section>${nav('profile')}`}

function renderCategory(){const c=category();patch({screen:'category'});app.innerHTML=`${header(true)}<section class="category-hero"><span>${c.icon}</span><div><span class="eyebrow">${tr('LERNWELT','MUNDO')}</span><h1>${c[s().lang]}</h1><p>${availableWords(c).length} ${tr('Wörter stehen aktuell bereit.','palabras disponibles.')}</p></div></section><div class="mode-list">${modes.map(m=>{const locked=!m.free&&!s().unlocked.includes(m.id);return `<button data-start="${m.id}" class="${locked?'locked':''}"><span>${m.icon}</span><div><strong>${m[s().lang]}</strong><small>${locked?`🐚 ${m.cost} · ${tr('in Boutique öffnen','abrir en boutique')}`:tr('Jetzt spielen','Jugar ahora')}</small></div><b>${locked?'🔒':'→'}</b></button>`}).join('')}</div>${nav('worlds')}`}

function start(mode){const m=modes.find(x=>x.id===mode);if(!m.free&&!s().unlocked.includes(mode)){patch({screen:'shop'});return render()}game={...game,mode,step:0,score:0,combo:0,items:shuffle(availableWords(category())).slice(0,Math.min(8,availableWords(category()).length)),selected:[],bank:[],matched:[],open:[],time:45};if(mode==='sentence'){patch({screen:'sentence'});newSentence()}else if(mode==='memory'){startMemory()}else if(mode==='speed'){patch({screen:'speed'});startSpeed()}else{patch({screen:'game'});renderGame()}}
function gameHead(title,total=game.items.length){return `${header(true)}<section class="game-head"><div class="progress"><i style="width:${Math.min(100,game.step/Math.max(1,total)*100)}%"></i></div><div><span>${title}</span><b>⭐ ${game.score}</b></div></section>`}
function renderGame(){if(game.step>=game.items.length)return finish();const cur=game.items[game.step];game.current=cur;if(game.mode==='learn'){app.innerHTML=`${gameHead(tr('Wörter entdecken','Descubrir palabras'))}<section class="flashcard"><span>${cur.emoji}</span><small>${category()[s().lang]}</small><h1>${cur[target()]}</h1><p>${cur[s().lang]}</p><button data-action="speak">🔊 ${tr('Anhören','Escuchar')}</button></section><button class="primary" data-action="next">${tr('Weiter','Siguiente')} →</button>`;setTimeout(()=>speak(cur[target()]),250);return}const opts=shuffle([cur,...shuffle(availableWords(category()).filter(w=>w.id!==cur.id)).slice(0,3)]);app.innerHTML=`${gameHead(game.mode==='quiz'?tr('Hör-Abenteuer','Aventura auditiva'):tr('Wort-Magie','Magia de palabras'))}<section class="question"><span>${game.mode==='quiz'?'🎧':cur.emoji}</span><h2>${game.mode==='quiz'?tr('Höre zu und finde das Bild','Escucha y encuentra la imagen'):tr('Welches Wort passt?','¿Qué palabra corresponde?')}</h2>${game.mode==='quiz'?'<button data-action="speak">🔊</button>':`<p>${cur[s().lang]}</p>`}</section><div class="answers">${opts.map(w=>`<button data-answer="${w.id}"><span>${game.mode==='quiz'?w.emoji:'✦'}</span><strong>${game.mode==='quiz'?w[s().lang]:w[target()]}</strong></button>`).join('')}</div>`;if(game.mode==='quiz')setTimeout(()=>speak(cur[target()]),200)}
function answer(id){if(id===game.current.id){game.score++;game.combo++;addReward({xp:10,shells:game.combo%3===0?2:0,daily:1});markLearned([id]);toast(game.combo>1?`✨ ${game.combo}× Combo`:'✓');setTimeout(()=>{game.step++;renderGame()},500)}else{game.combo=0;toast(tr('Fast! Versuch es noch einmal.','¡Casi! Inténtalo otra vez.'))}}

function newSentence(){if(game.step>=5)return finish();const item=sentences[(game.step+Math.floor(Math.random()*sentences.length))%sentences.length];game.current=item;game.selected=[];game.bank=shuffle(item[target()].map((text,i)=>({id:`${game.step}-${i}-${text}`,text})));renderSentence()}
function renderSentence(){const item=game.current;app.innerHTML=`${gameHead(tr('Satzwerkstatt','Taller de frases'),5)}<section class="sentence-guide"><div class="tula-mini">🐢</div><div><span class="eyebrow">${tr('BILDE DEN SATZ','FORMA LA FRASE')}</span><h2>${tr('Ziehe die Wörter in die richtige Reihenfolge','Arrastra las palabras en el orden correcto')}</h2><p>${tr('Der Satz unten ist deine Vorlage. Höre ihn an und baue ihn nach.','La frase de abajo es tu ejemplo.')}</p></div></section><section class="sentence-target"><span class="lang-badge">${s().lang.toUpperCase()}</span><strong>${item[s().lang].join(' ')}</strong><button data-action="speak-source">🔊</button></section><section class="sentence-board dropzone" data-zone="selected">${game.selected.length?game.selected.map(tileCard).join(''):`<div class="empty"><span>↓</span><strong>${tr('Ziehe die Wörter hierher','Arrastra las palabras aquí')}</strong><small>${tr('Du kannst sie danach noch verschieben.','Puedes reordenarlas después.')}</small></div>`}</section><section class="word-bank dropzone" data-zone="bank">${game.bank.map(tileCard).join('')}</section><div class="sentence-actions"><button data-action="sentence-reset">↺ ${tr('Neu mischen','Mezclar')}</button><button class="primary" data-action="sentence-check" ${game.selected.length!==item[target()].length?'disabled':''}>${tr('Prüfen','Comprobar')} ✓</button></div>`;enablePointerDrag()}
function tileCard(t){return `<button class="word-tile" data-tile="${t.id}"><span class="grip">⠿</span>${t.text}</button>`}
function moveTile(id,to,index=null){let from=game.bank.findIndex(x=>x.id===id),tile;if(from>=0)tile=game.bank.splice(from,1)[0];else{from=game.selected.findIndex(x=>x.id===id);if(from>=0)tile=game.selected.splice(from,1)[0]}if(!tile)return;const list=to==='selected'?game.selected:game.bank;if(index===null||index>list.length)list.push(tile);else list.splice(index,0,tile);renderSentence()}
function enablePointerDrag(){document.querySelectorAll('.word-tile').forEach(el=>{let ghost=null,startX=0,startY=0,moved=false;el.addEventListener('pointerdown',e=>{startX=e.clientX;startY=e.clientY;el.setPointerCapture(e.pointerId);ghost=el.cloneNode(true);ghost.classList.add('drag-ghost');document.body.appendChild(ghost);ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`});el.addEventListener('pointermove',e=>{if(!ghost)return;if(Math.hypot(e.clientX-startX,e.clientY-startY)>8)moved=true;ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`;document.querySelectorAll('.dropzone').forEach(z=>z.classList.toggle('over',z===document.elementFromPoint(e.clientX,e.clientY)?.closest('.dropzone')))});el.addEventListener('pointerup',e=>{ghost?.remove();document.querySelectorAll('.dropzone').forEach(z=>z.classList.remove('over'));if(!moved){moveTile(el.dataset.tile,el.closest('[data-zone]')?.dataset.zone==='selected'?'bank':'selected');return}const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-zone]');if(zone){const siblings=[...zone.querySelectorAll('.word-tile')];let index=siblings.findIndex(x=>e.clientX<x.getBoundingClientRect().left+x.offsetWidth/2);if(index<0)index=siblings.length;moveTile(el.dataset.tile,zone.dataset.zone,index)}else renderSentence()})})}
function checkSentence(){const correct=game.current[target()];const built=game.selected.map(x=>x.text);if(JSON.stringify(correct)===JSON.stringify(built)){game.score++;addReward({xp:18,shells:4,daily:1});markLearned([]);speak(correct.join(' '));toast(tr('Perfekt gebaut!','¡Perfecto!'));setTimeout(()=>{game.step++;newSentence()},800)}else toast(tr('Noch nicht ganz. Verschiebe die Karten noch einmal.','Aún no. Reordena las tarjetas.'))}

function startMemory(){const pairs=shuffle(availableWords(category())).slice(0,4);game.memory=shuffle(pairs.flatMap(w=>[{id:`${w.id}-a`,pair:w.id,label:w.emoji},{id:`${w.id}-b`,pair:w.id,label:w[target()]}]));game.open=[];game.matched=[];patch({screen:'memory'});renderMemory()}
function renderMemory(){if(game.matched.length===8)return finish();app.innerHTML=`${gameHead(tr('Palast-Memory','Memoria del palacio'),8)}<section class="memory-grid">${game.memory.map(c=>`<button data-memory="${c.id}" class="${game.open.includes(c.id)||game.matched.includes(c.id)?'open':''}"><span>${game.open.includes(c.id)||game.matched.includes(c.id)?c.label:'⚓'}</span></button>`).join('')}</section>`}
function memoryClick(id){if(game.open.includes(id)||game.matched.includes(id)||game.open.length===2)return;game.open.push(id);renderMemory();if(game.open.length===2){const a=game.memory.find(x=>x.id===game.open[0]),b=game.memory.find(x=>x.id===game.open[1]);setTimeout(()=>{if(a.pair===b.pair){game.matched.push(...game.open);game.score++;addReward({xp:8,shells:2,daily:1})}game.open=[];renderMemory()},650)}}
function startSpeed(){game.items=shuffle(categories.flatMap(c=>availableWords(c))).slice(0,40);game.step=0;game.time=45;game.timer=setInterval(()=>{game.time--;if(game.time<=0){clearTimer();finish()}else renderSpeed()},1000);renderSpeed()}
function renderSpeed(){if(game.step>=game.items.length)return finish();const cur=game.items[game.step];game.current=cur;const opts=shuffle([cur,...shuffle(categories.flatMap(c=>availableWords(c)).filter(w=>w.id!==cur.id)).slice(0,3)]);app.innerHTML=`${gameHead(tr('Goldene Minute','Minuto dorado'),game.items.length)}<section class="timer">⏱️ <strong>${game.time}</strong></section><section class="speed-word"><span>${cur.emoji}</span><h2>${cur[s().lang]}</h2></section><div class="word-options">${opts.map(w=>`<button data-speed="${w.id}">${w[target()]}</button>`).join('')}</div>`}
function speedAnswer(id){if(id===game.current.id){game.score++;game.combo++;addReward({xp:5,shells:game.combo%5===0?3:0,daily:1})}else game.combo=0;game.step++;renderSpeed()}

function finish(){clearTimer();const reward=addReward({xp:15,shells:Math.max(4,game.score*2),daily:0});patch({screen:'complete'});game.reward=reward;renderComplete()}
function renderComplete(){app.innerHTML=`${header()}<section class="complete"><div class="complete-art"><span>🐢</span><i>🐚</i></div><span class="eyebrow">${tr('LEKTION ABGESCHLOSSEN','LECCIÓN COMPLETADA')}</span><h1>${tr('Wunderbar!','¡Maravilloso!')}</h1><p>${tr('Du machst großartige Fortschritte.','Estás progresando genial.')}</p><div class="reward-grid"><div><span>⭐</span><strong>+${game.score}</strong><small>${tr('Punkte','Puntos')}</small></div><div><span>🐚</span><strong>+${game.reward?.shells||0}</strong><small>${tr('Muscheln','Conchas')}</small></div><div><span>✨</span><strong>+${game.reward?.xp||0}</strong><small>XP</small></div></div>${levelBar()}<div class="complete-actions"><button class="primary" data-action="home">⌂ ${tr('Zur Startseite','Ir al inicio')}</button><button data-action="category">📖 ${tr('Weitere Übung wählen','Elegir otro ejercicio')}</button><button data-screen="shop">♛ ${tr('Zur Muschel-Boutique','Ir a boutique')}</button></div></section>`}

function claimMilestone(lv){const m=milestones.find(x=>x.level===lv);if(!m||level()<lv||s().claimed.includes(lv))return;update(st=>{st.claimed=[...st.claimed,lv];if(lv===3)st.learned={...st.learned,'pack-animals':5};if(lv===5)st.boosters={...st.boosters,doubleXpUntil:Date.now()+86400000};if(lv===7)st.shells+=100;if(lv===10)st.boosters={...st.boosters,jumps:(st.boosters.jumps||0)+3};return st});toast(tr('Belohnung freigeschaltet!','¡Recompensa desbloqueada!'));renderProfile()}
function buyMode(id){const m=modes.find(x=>x.id===id);if(!m||s().unlocked.includes(id))return;if(!buy(m.cost))return toast(tr('Nicht genug Muscheln.','No hay suficientes conchas.'));patch({unlocked:[...s().unlocked,id]});toast(tr('Modus freigeschaltet!','¡Modo desbloqueado!'));renderShop()}
function buyBooster(id){const b=boosters.find(x=>x.id===id);if(!buy(b.cost))return toast(tr('Nicht genug Muscheln.','No hay suficientes conchas.'));update(st=>{if(id==='doubleXp')st.boosters.doubleXpUntil=Date.now()+86400000;if(id==='jump')st.boosters.jumps=(st.boosters.jumps||0)+1;if(id==='hint')st.boosters.hints=(st.boosters.hints||0)+1;return st});toast(tr('Booster aktiviert!','¡Mejora activada!'));renderShop()}
function buyPack(id){const c=categories.find(x=>x.id===id),count=Number(s().learned[`pack-${id}`]||0);if(8+count*4>=c.words.length)return;if(!buy(50))return toast(tr('Nicht genug Muscheln.','No hay suficientes conchas.'));update(st=>{st.learned={...st.learned,[`pack-${id}`]:count+1};return st});toast(tr('Vier neue Wörter freigeschaltet!','¡Cuatro palabras nuevas!'));renderLibrary()}
function toast(text){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}

app.addEventListener('click',e=>{const screen=e.target.closest('[data-screen]')?.dataset.screen,open=e.target.closest('[data-open-category]')?.dataset.openCategory,action=e.target.closest('[data-action]')?.dataset.action,startMode=e.target.closest('[data-start]')?.dataset.start,answerId=e.target.closest('[data-answer]')?.dataset.answer,memory=e.target.closest('[data-memory]')?.dataset.memory,speed=e.target.closest('[data-speed]')?.dataset.speed,mode=e.target.closest('[data-buy-mode]')?.dataset.buyMode,booster=e.target.closest('[data-buy-booster]')?.dataset.buyBooster,pack=e.target.closest('[data-pack]')?.dataset.pack,claim=e.target.closest('[data-claim]')?.dataset.claim;if(screen){patch({screen});render()}if(open){patch({category:open,screen:'category'});render()}if(startMode)start(startMode);if(answerId)answer(answerId);if(memory)memoryClick(memory);if(speed)speedAnswer(speed);if(mode)buyMode(mode);if(booster)buyBooster(booster);if(pack)buyPack(pack);if(claim)claimMilestone(Number(claim));if(action==='back'){patch({screen:['game','sentence','memory','speed'].includes(s().screen)?'category':'home'});render()}if(action==='home'){patch({screen:'home'});render()}if(action==='category'){patch({screen:'category'});render()}if(action==='next'){game.step++;addReward({xp:5,shells:1,daily:1});markLearned([game.current.id]);renderGame()}if(action==='speak')speak(game.current[target()]);if(action==='speak-source')speak(game.current[s().lang],s().lang);if(action==='sentence-reset')newSentence();if(action==='sentence-check')checkSentence();if(action==='settings'){patch({sound:!s().sound});toast(s().sound?'🔊 Audio an':'🔇 Audio aus')}});

if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
