const worlds=[
{id:'animals',icon:'🦊',de:'Tiere',es:'Animales',words:[['🐶','Hund','perro'],['🐱','Katze','gato'],['🐦','Vogel','pájaro'],['🐟','Fisch','pez'],['🐴','Pferd','caballo'],['🐮','Kuh','vaca'],['🐰','Kaninchen','conejo'],['🦁','Löwe','león']]},
{id:'food',icon:'🍓',de:'Essen',es:'Comida',words:[['🍎','Apfel','manzana'],['🍌','Banane','plátano'],['🍞','Brot','pan'],['🥛','Milch','leche'],['🧀','Käse','queso'],['💧','Wasser','agua'],['🍓','Erdbeere','fresa'],['🥕','Karotte','zanahoria']]},
{id:'home',icon:'🏡',de:'Zuhause',es:'Casa',words:[['🚪','Tür','puerta'],['🪟','Fenster','ventana'],['🛏️','Bett','cama'],['🪑','Stuhl','silla'],['🛋️','Sofa','sofá'],['💡','Lampe','lámpara'],['🧸','Teddy','peluche'],['🗝️','Schlüssel','llave']]}
];
const modes=[
{id:'learn',icon:'◉',de:'Wörter entdecken',es:'Descubrir palabras',free:true,desc:'Ansehen, hören und merken'},
{id:'quiz',icon:'♫',de:'Hör-Abenteuer',es:'Aventura auditiva',free:true,desc:'Hören und das richtige Bild wählen'},
{id:'match',icon:'◇',de:'Wort-Magie',es:'Magia de palabras',free:true,desc:'Bild und Übersetzung verbinden'},
{id:'sentence',icon:'✒',de:'Satzwerkstatt',es:'Taller de frases',cost:80,desc:'Wörter ziehen und Sätze bauen'},
{id:'memory',icon:'♜',de:'Palast-Memory',es:'Memoria del palacio',cost:120,desc:'Bild und Wort als Paare finden'},
{id:'speed',icon:'⚡',de:'Goldene Minute',es:'Minuto dorado',cost:160,desc:'Schnelle Aufgaben und Combo-Boni'}
];
const sentences=[
{de:['Der','Hund','rennt','.'],es:['El','perro','corre','.']},
{de:['Die','Katze','schläft','.'],es:['El','gato','duerme','.']},
{de:['Ich','esse','einen','Apfel','.'],es:['Yo','como','una','manzana','.']},
{de:['Das','Wasser','ist','kalt','.'],es:['El','agua','está','fría','.']},
{de:['Wo','ist','mein','Teddy','?'],es:['¿','Dónde','está','mi','peluche','?']},
{de:['Die','Lampe','ist','gelb','.'],es:['La','lámpara','es','amarilla','.']}
];
const KEY='linguaturtle-hellenic-v5';
const old=JSON.parse(localStorage.getItem('linguaturtle-premium-v4')||'{}');
const prior=JSON.parse(localStorage.getItem(KEY)||'{}');
const today=new Date().toISOString().slice(0,10);
const state={
 lang:prior.lang||old.lang||'de',shells:prior.shells??old.shells??75,xp:prior.xp??old.xp??0,
 unlocked:prior.unlocked||old.unlocked||[],world:prior.world||old.world||'animals',muted:prior.muted??old.muted??false,
 dailyDate:prior.dailyDate===today?today:today,dailyCount:prior.dailyDate===today?(prior.dailyCount||0):0,
 streak:prior.streak||1,lastReward:prior.lastReward||'',screen:'home',mode:null,step:0,score:0,combo:0,
 order:[],selected:[],bank:[],memory:[],open:[],matched:[],timer:null,time:45,currentSentence:null
};
const app=document.querySelector('#app');
const tr=(de,es)=>state.lang==='de'?de:es;
const world=()=>worlds.find(w=>w.id===state.world)||worlds[0];
const target=()=>state.lang==='de'?'es':'de';
const level=()=>Math.floor(state.xp/100)+1;
const levelXP=()=>state.xp%100;
const xpLeft=()=>100-levelXP();
function save(){localStorage.setItem(KEY,JSON.stringify({lang:state.lang,shells:state.shells,xp:state.xp,unlocked:state.unlocked,world:state.world,muted:state.muted,dailyDate:today,dailyCount:state.dailyCount,streak:state.streak,lastReward:state.lastReward}));}
function speak(text,lang=target()){if(state.muted||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='de'?'de-DE':'es-ES';u.rate=.78;u.pitch=1.03;speechSynthesis.speak(u);}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function wordObj(row){return{emoji:row[0],de:row[1],es:row[2],id:row[1].toLowerCase()}}
function clearTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}}
function header(back=false){return `<header class="topbar"><button class="round ${back?'':'invisible'}" data-act="${state.screen==='shop'?'home':state.screen==='world'?'home':state.screen==='home'?'home':'world'}">←</button><div class="brand"><span class="brand-shell">🐢</span><b>LinguaTurtle</b></div><button class="currency" data-act="shop">🐚 <b>${state.shells}</b></button></header>`}
function particles(){return `<div class="ambient" aria-hidden="true"><i>✦</i><i>·</i><i>✧</i><i>·</i><i>✦</i></div>`}
function progressCard(){return `<section class="level-card"><div class="level-head"><div><small>${tr('Lernstufe','Nivel')} ${level()}</small><strong>${state.xp} XP</strong></div><span>${xpLeft()} XP ${tr('bis Stufe','hasta nivel')} ${level()+1}</span></div><div class="level-track"><i style="width:${levelXP()}%"></i></div></section>`}
function dailyCard(){const done=Math.min(5,state.dailyCount);return `<section class="daily-card"><div class="daily-title"><div><span>☀️</span><div><small>${tr('Tagesziel','Meta diaria')}</small><strong>${done}/5 ${tr('Aufgaben','tareas')}</strong></div></div><span>${done>=5?'✓ '+tr('Geschafft','Completado'):'+'+(5-done)}</span></div><div class="daily-dots">${[0,1,2,3,4].map(i=>`<i class="${i<done?'done':''}">${i<done?'✓':'·'}</i>`).join('')}</div><p>${done>=5?tr('Belohnung eingesammelt: 10 Muscheln','Recompensa: 10 conchas'):tr('Schließe heute fünf Aufgaben ab und erhalte 10 Muscheln.','Completa cinco tareas y recibe 10 conchas.')}</p></section>`}
function renderHome(){clearTimer();state.screen='home';app.innerHTML=`${particles()}${header()}<section class="hero-premium"><div><span class="eyebrow">${tr('Deine Sprachreise','Tu viaje lingüístico')}</span><h1>${tr('Haus der Wörter','Casa de las palabras')}</h1><p>${tr('Lerne spielerisch, sammle Muscheln und öffne neue Räume.','Aprende jugando, recoge conchas y abre nuevas salas.')}</p></div><div class="tula-stage"><span class="halo"></span><span class="tula">🐢</span><small>${tr('Tula wartet auf dich','Tula te espera')}</small></div></section>${progressCard()}${dailyCard()}<section class="dashboard"><div><small>🔥 ${tr('Lernserie','Racha')}</small><strong>${state.streak}</strong></div><div><small>🐚 ${tr('Muscheln','Conchas')}</small><strong>${state.shells}</strong></div><button data-act="shop"><small>${tr('Muschel-Boutique','Boutique')}</small><strong>Shop ›</strong></button></section><section class="section-title"><div><span class="eyebrow">${tr('Die Lernwelten','Los mundos')}</span><h2>${tr('Wähle deinen nächsten Raum','Elige tu próxima sala')}</h2></div><button class="text-btn" data-act="language">${state.lang==='de'?'🇩🇪 DE':'🇪🇸 ES'}</button></section><div class="worlds">${worlds.map((w,i)=>`<button class="world-card ${w.id===state.world?'active':''}" data-world="${w.id}"><span class="number">0${i+1}</span><div class="world-art">${w.icon}</div><div><strong>${w[state.lang]}</strong><small>8 ${tr('ausgewählte Wörter','palabras elegidas')}</small></div><b>→</b></button>`).join('')}</div><button class="grand-button" data-act="openWorld"><span>${world().icon}</span><div><small>${tr('Weiterlernen','Seguir aprendiendo')}</small><strong>${world()[state.lang]}</strong></div><b>→</b></button><p class="footer-note">${tr('Ruhig gestaltet · ohne Werbung · Fortschritt nur auf diesem Gerät','Diseño tranquilo · sin publicidad')}</p>`}
function renderWorld(){state.screen='world';app.innerHTML=`${particles()}${header(true)}<section class="room-hero"><div><span class="eyebrow">${tr('Lernsalon','Salón de aprendizaje')}</span><h1>${world()[state.lang]}</h1><p>${tr('Wähle eine Übung. Drei besondere Räume kannst du mit Muscheln öffnen.','Elige un ejercicio. Puedes abrir tres salas especiales con conchas.')}</p></div><span>${world().icon}</span></section>${progressCard()}<div class="mode-list">${modes.map(m=>{const locked=!m.free&&!state.unlocked.includes(m.id);return `<button class="mode-card ${locked?'locked':''}" data-mode="${m.id}"><span class="mode-medallion">${m.icon}</span><div><strong>${m[state.lang]}</strong><small>${m.desc}</small></div>${locked?`<em>🐚 ${m.cost}</em>`:'<b>›</b>'}</button>`}).join('')}</div><button class="boutique-banner" data-act="shop"><span>♛</span><div><small>${tr('Muschel-Boutique','Boutique de conchas')}</small><strong>${tr('Neue Spielmodi freischalten','Desbloquear nuevos modos')}</strong></div><b>→</b></button>`}
function renderShop(){state.screen='shop';app.innerHTML=`${particles()}${header(true)}<section class="shop-hero"><span>♛</span><div><span class="eyebrow">${tr('Tulas Muschel-Boutique','Boutique de Tula')}</span><h1>${tr('Besondere Lernräume','Salas especiales')}</h1><p>${tr('Muscheln werden nur erspielt. Hier gibt es keine echten Käufe.','Las conchas solo se ganan jugando.')}</p></div></section><div class="wallet">🐚 <strong>${state.shells}</strong><small>${tr('verfügbare Muscheln','conchas disponibles')}</small></div><div class="shop-grid">${modes.filter(m=>!m.free).map(m=>{const owned=state.unlocked.includes(m.id);return `<article class="shop-item ${owned?'owned':''}"><span class="shop-icon">${m.icon}</span><span class="eyebrow">${owned?tr('Freigeschaltet','Desbloqueado'):tr('Premium-Modus','Modo premium')}</span><h2>${m[state.lang]}</h2><p>${m.desc}</p><button data-buy="${m.id}" ${owned?'disabled':''}>${owned?`✓ ${tr('Bereits geöffnet','Ya abierto')}`:`🐚 ${m.cost} · ${tr('Freischalten','Desbloquear')}`}</button></article>`}).join('')}</div><section class="earn-box"><strong>${tr('Belohnungen','Recompensas')}</strong><p>${tr('Jede Runde bringt XP und Muscheln. Tagesziele, Combos und Stufenaufstiege geben zusätzliche Boni.','Cada ronda da XP y conchas. Las metas y combos dan bonos.')}</p></section>`}
function buy(id){const m=modes.find(x=>x.id===id);if(!m||state.unlocked.includes(id))return;if(state.shells<m.cost){toast(tr('Noch nicht genug Muscheln.','Aún no tienes suficientes conchas.'));return}state.shells-=m.cost;state.unlocked.push(id);save();celebrate();renderShop()}
function startMode(id){const m=modes.find(x=>x.id===id);if(!m)return;if(!m.free&&!state.unlocked.includes(id)){renderShop();return}state.mode=id;state.step=0;state.score=0;state.combo=0;state.order=shuffle(world().words.map(wordObj)).slice(0,6);if(id==='sentence')renderSentence();else if(id==='memory')startMemory();else if(id==='speed')startSpeed();else renderBasic()}
function activityHead(title,total=state.order.length){return `${header(true)}<section class="activity-title"><div class="progress"><i style="width:${Math.min(100,(state.step/Math.max(1,total))*100)}%"></i></div><div><span>${title}</span><b>⭐ ${state.score}</b></div></section>`}
function renderBasic(){if(state.step>=state.order.length)return finish();state.screen='activity';const cur=state.order[state.step];const opts=shuffle([cur,...shuffle(world().words.map(wordObj).filter(x=>x.id!==cur.id)).slice(0,3)]);if(state.mode==='learn'){app.innerHTML=`${activityHead(tr('Wörter entdecken','Descubrir palabras'))}<section class="museum-card"><span class="frame-ornament">✦</span><div class="giant-emoji">${cur.emoji}</div><span class="eyebrow">${world()[state.lang]}</span><h1>${cur[target()]}</h1><p>${cur[state.lang]}</p><button class="listen" data-act="speak">🔊 ${tr('Anhören','Escuchar')}</button></section><button class="grand-button compact" data-act="next"><div><strong>${tr('Weiter','Siguiente')}</strong></div><b>→</b></button>`;setTimeout(()=>speak(cur[target()]),200);return}const question=state.mode==='quiz'?tr('Hör zu und wähle das richtige Bild','Escucha y elige la imagen correcta'):tr('Welches Wort gehört zu diesem Bild?','¿Qué palabra corresponde a esta imagen?');app.innerHTML=`${activityHead(state.mode==='quiz'?tr('Hör-Abenteuer','Aventura auditiva'):tr('Wort-Magie','Magia de palabras'))}<section class="question-box"><span>${state.mode==='quiz'?'🎧':cur.emoji}</span><h2>${question}</h2>${state.mode==='quiz'?'<button class="listen round-listen" data-act="speak">🔊</button>':`<small>${cur[state.lang]}</small>`}</section><div class="answers">${opts.map(o=>`<button data-answer="${o.id}"><span>${state.mode==='quiz'?o.emoji:'✦'}</span><strong>${state.mode==='quiz'?o[state.lang]:o[target()]}</strong></button>`).join('')}</div>`;if(state.mode==='quiz')setTimeout(()=>speak(cur[target()]),180)}
function awardTask(xp=10,shells=1){const before=level();state.xp+=xp;state.shells+=shells;state.dailyCount++;if(state.dailyCount===5&&state.lastReward!==today){state.shells+=10;state.lastReward=today;toast(tr('Tagesziel geschafft: +10 Muscheln!','Meta diaria: +10 conchas!'))}if(level()>before){state.shells+=15;toast(`${tr('Stufenaufstieg','Subida de nivel')}! +15 🐚`);celebrate()}save()}
function answer(id){const cur=state.order[state.step];if(id===cur.id){state.score++;state.combo++;awardTask(10,state.combo>=3?2:1);toast(`${tr('Wunderbar','Excelente')}${state.combo>1?` · ${state.combo}× Combo`:''}`);speak(cur[target()]);setTimeout(()=>{state.step++;renderBasic()},600)}else{state.combo=0;toast(tr('Fast – probiere es noch einmal','Casi, inténtalo otra vez'))}}
function renderSentence(){state.screen='sentence';if(state.step>=4)return finish();const s=sentences[(state.step+2)%sentences.length];state.currentSentence=s;state.selected=[];state.bank=shuffle(s[target()].map((text,i)=>({text,id:`${state.step}-${i}-${text}`})));drawSentence()}
function tileHTML(x,source){return `<button class="sentence-tile" data-drag-id="${x.id}" data-source="${source}" type="button"><span class="grip">⋮⋮</span>${x.text}</button>`}
function drawSentence(message=''){const s=state.currentSentence;app.innerHTML=`${activityHead(tr('Satzwerkstatt','Taller de frases'),4)}<section class="sentence-intro"><span>✒</span><div><h2>${tr('Baue den Satz','Construye la frase')}</h2><p>${tr('Ziehe die Wortkarten mit dem Finger. Tippen funktioniert zusätzlich.','Arrastra las tarjetas con el dedo. También puedes tocarlas.')}</p></div></section><div class="translation-clue">${s[state.lang].join(' ')}</div><section class="sentence-board drop-zone" id="sentenceBoard">${state.selected.length?state.selected.map(x=>tileHTML(x,'selected')).join(''):`<small>${tr('Wörter hierher ziehen …','Arrastra palabras aquí …')}</small>`}</section><section class="word-bank drop-zone" id="wordBank">${state.bank.map(x=>tileHTML(x,'bank')).join('')}</section><div class="sentence-actions"><button data-act="sentenceReset">↺ ${tr('Neu ordnen','Reordenar')}</button><button class="check" data-act="sentenceCheck">${tr('Prüfen','Comprobar')} ✓</button></div>${message}`;enablePointerDrag()}
function moveBetween(id,to,index=null){let item;let i=state.bank.findIndex(x=>x.id===id);if(i>=0)item=state.bank.splice(i,1)[0];else{ i=state.selected.findIndex(x=>x.id===id);if(i>=0)item=state.selected.splice(i,1)[0]}if(!item)return;const arr=to==='selected'?state.selected:state.bank;if(index==null||index<0||index>arr.length)arr.push(item);else arr.splice(index,0,item);drawSentence()}
function enablePointerDrag(){let drag=null;document.querySelectorAll('.sentence-tile').forEach(tile=>{tile.addEventListener('click',()=>moveBetween(tile.dataset.dragId,tile.dataset.source==='bank'?'selected':'bank'));tile.addEventListener('pointerdown',e=>{e.preventDefault();const r=tile.getBoundingClientRect();drag={id:tile.dataset.dragId,source:tile.dataset.source,el:tile,ghost:tile.cloneNode(true),offX:e.clientX-r.left,offY:e.clientY-r.top};drag.ghost.classList.add('drag-ghost');drag.ghost.style.width=`${r.width}px`;document.body.appendChild(drag.ghost);tile.classList.add('dragging');tile.setPointerCapture(e.pointerId);positionGhost(e)});tile.addEventListener('pointermove',e=>{if(!drag)return;positionGhost(e);markDrop(e)});tile.addEventListener('pointerup',e=>dropPointer(e));tile.addEventListener('pointercancel',e=>dropPointer(e))});function positionGhost(e){drag.ghost.style.left=`${e.clientX-drag.offX}px`;drag.ghost.style.top=`${e.clientY-drag.offY}px`}function markDrop(e){document.querySelectorAll('.drop-zone').forEach(z=>z.classList.remove('drop-active'));document.elementFromPoint(e.clientX,e.clientY)?.closest('.drop-zone')?.classList.add('drop-active')}function dropPointer(e){if(!drag)return;const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('.drop-zone');const target=zone?.id==='sentenceBoard'?'selected':zone?.id==='wordBank'?'bank':null;drag.el.classList.remove('dragging');drag.ghost.remove();document.querySelectorAll('.drop-zone').forEach(z=>z.classList.remove('drop-active'));const id=drag.id;drag=null;if(target){const children=[...zone.querySelectorAll('.sentence-tile')];let index=children.findIndex(c=>e.clientX<c.getBoundingClientRect().left+c.offsetWidth/2);if(index<0)index=children.length;moveBetween(id,target,index)}}}
function checkSentence(){const correct=state.currentSentence[target()].join('|');const made=state.selected.map(x=>x.text).join('|');if(made===correct){state.score++;awardTask(18,3);speak(state.selected.map(x=>x.text).join(' '));celebrate();toast(tr('Perfekter Satz!','¡Frase perfecta!'));setTimeout(()=>{state.step++;renderSentence()},900)}else{drawSentence(`<section class="sentence-hint">${tr('Noch nicht ganz. Verschiebe die Karten noch einmal.','Aún no. Mueve las tarjetas de nuevo.')}</section>`);}}
function startMemory(){state.screen='memory';const chosen=shuffle(world().words.map(wordObj)).slice(0,4);state.memory=shuffle(chosen.flatMap(w=>[{key:w.id,type:'emoji',value:w.emoji},{key:w.id,type:'word',value:w[target()]}]));state.open=[];state.matched=[];drawMemory()}
function drawMemory(){app.innerHTML=`${activityHead(tr('Palast-Memory','Memoria del palacio'),4)}<section class="memory-grid">${state.memory.map((c,i)=>{const shown=state.open.includes(i)||state.matched.includes(c.key);return `<button class="memory-card ${shown?'shown':''}" data-memory="${i}">${shown?c.value:'♜'}</button>`}).join('')}</section><p class="center-note">${state.matched.length}/4 ${tr('Paare gefunden','parejas')}</p>`}
function memoryClick(i){if(state.open.includes(i)||state.matched.includes(state.memory[i].key)||state.open.length>=2)return;state.open.push(i);drawMemory();if(state.open.length===2){const[a,b]=state.open;if(state.memory[a].key===state.memory[b].key){state.matched.push(state.memory[a].key);state.open=[];state.score++;awardTask(8,1);if(state.matched.length===4)setTimeout(finish,600);else setTimeout(drawMemory,250)}else setTimeout(()=>{state.open=[];drawMemory()},650)}}
function startSpeed(){state.screen='speed';state.time=45;state.step=0;state.score=0;state.order=shuffle(world().words.map(wordObj));drawSpeed();state.timer=setInterval(()=>{state.time--;const el=document.querySelector('[data-time]');if(el)el.textContent=state.time;if(state.time<=0){clearTimer();finish()}},1000)}
function drawSpeed(){const cur=state.order[state.step%state.order.length];const opts=shuffle([cur,...shuffle(world().words.map(wordObj).filter(x=>x.id!==cur.id)).slice(0,2)]);app.innerHTML=`${header(true)}<section class="speed-head"><div><small>${tr('Goldene Minute','Minuto dorado')}</small><strong>⏱ <span data-time>${state.time}</span></strong></div><span>⚡ ${state.combo}×</span></section><section class="question-box"><span>${cur.emoji}</span><h2>${cur[state.lang]}</h2></section><div class="answers speed-answers">${opts.map(o=>`<button data-speed="${o.id}"><strong>${o[target()]}</strong></button>`).join('')}</div>`}
function speedAnswer(id){const cur=state.order[state.step%state.order.length];if(id===cur.id){state.combo++;state.score++;awardTask(4,state.combo%5===0?2:0);state.step++}else state.combo=0;drawSpeed()}
function finish(){clearTimer();const gain=Math.max(3,Math.ceil(state.score/2));state.shells+=gain;save();state.screen='reward';app.innerHTML=`${particles()}${header(true)}<section class="reward-room"><div class="reward-rays"></div><span class="reward-shell">🐚</span><span class="eyebrow">${tr('Belohnung','Recompensa')}</span><h1>${tr('Fantastisch gelernt!','¡Aprendiste genial!')}</h1><p>${tr('Deine Reise wächst mit jeder Aufgabe.','Tu viaje crece con cada tarea.')}</p><div class="reward-stats"><div><small>XP</small><strong>${state.xp}</strong></div><div><small>🐚</small><strong>+${gain}</strong></div><div><small>${tr('Combo','Combo')}</small><strong>${state.combo}</strong></div></div>${progressCard()}<button class="grand-button" data-act="world"><span>${world().icon}</span><div><small>${tr('Weiter','Continuar')}</small><strong>${world()[state.lang]}</strong></div><b>→</b></button></section>`;celebrate()}
function toast(text){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function celebrate(){for(let i=0;i<14;i++){const s=document.createElement('i');s.className='celebration';s.textContent=i%3?'✦':'🐚';s.style.left=`${10+Math.random()*80}%`;s.style.animationDelay=`${Math.random()*.3}s`;document.body.appendChild(s);setTimeout(()=>s.remove(),1800)}}
app.addEventListener('click',e=>{const act=e.target.closest('[data-act]')?.dataset.act;const wid=e.target.closest('[data-world]')?.dataset.world;const mode=e.target.closest('[data-mode]')?.dataset.mode;const buyId=e.target.closest('[data-buy]')?.dataset.buy;const ans=e.target.closest('[data-answer]')?.dataset.answer;const mem=e.target.closest('[data-memory]')?.dataset.memory;const speed=e.target.closest('[data-speed]')?.dataset.speed;if(wid){state.world=wid;save();renderHome()}if(mode)startMode(mode);if(buyId)buy(buyId);if(ans)answer(ans);if(mem!==undefined)memoryClick(Number(mem));if(speed)speedAnswer(speed);if(act==='home')renderHome();if(act==='world')renderWorld();if(act==='shop')renderShop();if(act==='openWorld')renderWorld();if(act==='language'){state.lang=state.lang==='de'?'es':'de';save();renderHome()}if(act==='speak'){const cur=state.order[state.step];if(cur)speak(cur[target()])}if(act==='next'){awardTask(5,1);state.score++;state.step++;renderBasic()}if(act==='sentenceReset')renderSentence();if(act==='sentenceCheck')checkSentence()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});renderHome();