import {collections} from './content.js';

const KEY='linguaturtle-v3-preview';
const stored=JSON.parse(localStorage.getItem(KEY)||'{}');
const state={screen:'home',lang:stored.lang||'de',xp:stored.xp||245,shells:stored.shells||182,streak:stored.streak||5,level:stored.level||5,daily:stored.daily||3,learned:stored.learned||{},collection:stored.collection||'garden'};
const game={items:[],step:0,score:0,current:null};
const app=document.querySelector('#app');
const t=(de,es)=>state.lang==='de'?de:es;
const target=()=>state.lang==='de'?'es':'de';
const selectedCollection=()=>collections.find(c=>c.id===state.collection)||collections[0];
const xpInLevel=()=>state.xp%100;
const xpMissing=()=>100-xpInLevel();
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function save(){localStorage.setItem(KEY,JSON.stringify({lang:state.lang,xp:state.xp,shells:state.shells,streak:state.streak,level:state.level,daily:state.daily,learned:state.learned,collection:state.collection}))}
function speak(text,lang=target()){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='de'?'de-DE':'es-ES';u.rate=.8;speechSynthesis.speak(u)}
function top(back=false){return `<header class="v3-top"><button class="icon" data-action="${back?'back':'menu'}">${back?'←':'☰'}</button><div class="v3-brand"><i>🐢</i><strong>LinguaTurtle</strong></div><button class="chip" data-action="language">${state.lang==='de'?'🇩🇪 DE':'🇪🇸 ES'}</button></header>`}
function nav(active){return `<nav class="v3-nav">${[['home','⌂',t('Home','Inicio')],['island','◉',t('Insel','Isla')],['library','▤',t('Wörter','Palabras')],['shop','♛',t('Shop','Tienda')],['profile','♙',t('Profil','Perfil')]].map(([id,icon,label])=>`<button class="${active===id?'active':''}" data-screen="${id}"><span>${icon}</span><small>${label}</small></button>`).join('')}</nav>`}
function progress(){return `<section class="progress-card"><div class="progress-head"><strong>${t('Level','Nivel')} ${state.level}</strong><span>${t(`Noch ${xpMissing()} XP bis Level ${state.level+1}`,`Faltan ${xpMissing()} XP para nivel ${state.level+1}`)}</span></div><div class="bar"><i style="width:${xpInLevel()}%"></i></div></section>`}
function renderHome(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="hero-v3"><div class="hero-copy"><span class="eyebrow">TURTLE ISLAND</span><h1>${t('Komm mit auf die Insel!','¡Ven a la isla!')}</h1><p>${t('Tula wartet auf dein nächstes Sprachabenteuer.','Tula espera tu próxima aventura lingüística.')}</p><button class="chip" data-screen="island">${t('Insel entdecken','Descubrir la isla')} →</button></div><img class="tula-art" src="assets/illustrations/tula-welcome.svg" alt="Tula die Schildkröte"></section><section class="stats-v3"><div><span>✨</span><strong>${state.xp}</strong><small>XP</small></div><div><span>🐚</span><strong>${state.shells}</strong><small>${t('Muscheln','Conchas')}</small></div><div><span>🔥</span><strong>${state.streak}</strong><small>${t('Lerntage','Días')}</small></div></section>${progress()}<div class="section-head"><div><span class="eyebrow">${t('HEUTE','HOY')}</span><h2>${t('Dein nächstes Abenteuer','Tu próxima aventura')}</h2></div></div><section class="journey-grid">${collections.map(c=>`<button data-place="${c.id}"><span>${c.icon}</span><div><strong>${c[state.lang]}</strong><small>${state.learned[c.id]||0}/${c.words.length} ${t('Wörter entdeckt','palabras descubiertas')}</small></div><b>→</b></button>`).join('')}</section><button class="island-card" data-screen="island"><img src="assets/illustrations/turtle-island.svg" alt="Karte von Turtle Island"><span class="island-info"><span><strong>${t('Deine Lerninsel','Tu isla de aprendizaje')}</strong><small>${t('Bibliothek und Garten sind geöffnet','Biblioteca y jardín abiertos')}</small></span><b>→</b></span></button></div>${nav('home')}`}
function renderIsland(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="page-title"><span class="eyebrow">TURTLE ISLAND</span><h1>${t('Wohin möchtest du?','¿Adónde quieres ir?')}</h1><p>${t('Jeder Ort öffnet einen anderen Teil deiner Sprachreise.','Cada lugar abre una parte distinta de tu viaje.')}</p></section><button class="island-card"><img src="assets/illustrations/turtle-island.svg" alt="Turtle Island"></button><div class="section-head"><div><span class="eyebrow">${t('ORTE','LUGARES')}</span><h2>${t('Wähle ein Abenteuer','Elige una aventura')}</h2></div></div><section class="places">${collections.map(c=>`<button class="place" data-place="${c.id}"><span>${c.icon}</span><strong>${c[state.lang]}</strong><small>${c[state.lang==='de'?'subtitleDe':'subtitleEs']}</small></button>`).join('')}<button class="place locked"><span>⚓</span><strong>${t('Hafen','Puerto')}</strong><small>${t('Ab Level 7','Desde nivel 7')}</small></button><button class="place locked"><span>🏰</span><strong>${t('Schloss','Castillo')}</strong><small>${t('Ab Level 10','Desde nivel 10')}</small></button></section></div>${nav('island')}`}
function renderCollection(){const c=selectedCollection();app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="place-hero"><span>${c.icon}</span><div><span class="eyebrow">${c.id==='garden'?t('TULAS GARTEN','EL JARDÍN DE TULA'):t('INSELBIBLIOTHEK','BIBLIOTECA DE LA ISLA')}</span><h1>${c[state.lang]}</h1><p>${c[state.lang==='de'?'subtitleDe':'subtitleEs']}</p></div></section><section class="mode-picker"><button data-mode="explore"><span>👀</span><div><strong>${t('Wörter entdecken','Descubrir palabras')}</strong><small>${t('Antippen, ansehen und anhören','Tocar, mirar y escuchar')}</small></div><b>→</b></button><button data-mode="quiz"><span>🎧</span><div><strong>${t('Hör-Abenteuer','Aventura auditiva')}</strong><small>${t('6 Fragen · bis zu 18 Muscheln','6 preguntas · hasta 18 conchas')}</small></div><b>→</b></button></section><div class="word-showcase">${c.words.slice(0,8).map(w=>`<article><span>${w.emoji}</span><strong>${w[state.lang]}</strong><small>${w[target()]}</small></article>`).join('')}</div></div>${nav(c.id==='library'?'library':'island')}`}
function renderExplore(){const c=selectedCollection();app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="page-title"><span class="eyebrow">${t('WÖRTER ENTDECKEN','DESCUBRIR PALABRAS')}</span><h1>${c[state.lang]}</h1><p>${t('Tippe eine Karte an, um das Wort zu hören.','Toca una tarjeta para escuchar la palabra.')}</p></section><div class="explore-grid">${c.words.map(w=>`<button data-speak-word="${w.id}"><span>${w.emoji}</span><strong>${w[target()]}</strong><small>${w[state.lang]}</small><em>🔊</em></button>`).join('')}</div></div>${nav(c.id==='library'?'library':'island')}`}
function startQuiz(){game.items=shuffle(selectedCollection().words).slice(0,6);game.step=0;game.score=0;renderQuiz()}
function renderQuiz(){if(game.step>=game.items.length)return finishQuiz();const c=selectedCollection(),cur=game.items[game.step];game.current=cur;const opts=shuffle([cur,...shuffle(c.words.filter(w=>w.id!==cur.id)).slice(0,3)]);app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="quiz-head"><div class="bar"><i style="width:${game.step/game.items.length*100}%"></i></div><span>${game.step+1}/${game.items.length}</span></section><section class="listen-card"><span>🎧</span><h2>${t('Hör gut zu','Escucha con atención')}</h2><p>${t('Welches Bild gehört zum Wort?','¿Qué imagen corresponde?')}</p><button data-action="repeat">🔊 ${t('Noch einmal','Otra vez')}</button></section><div class="quiz-grid">${opts.map(w=>`<button data-answer="${w.id}"><span>${w.emoji}</span><strong>${w[state.lang]}</strong></button>`).join('')}</div></div>`;setTimeout(()=>speak(cur[target()]),250)}
function answer(id){if(id!==game.current.id){toast(t('Fast! Versuch es noch einmal.','¡Casi! Inténtalo otra vez.'));return}game.score++;game.step++;state.xp+=10;state.shells+=2;state.daily=Math.min(5,state.daily+1);state.learned[state.collection]=Math.max(state.learned[state.collection]||0,game.step);if(state.xp>=state.level*100)state.level++;save();toast(t('Sehr gut! +2 Muscheln','¡Muy bien! +2 conchas'));setTimeout(renderQuiz,500)}
function finishQuiz(){const bonus=game.score*2+6;state.shells+=6;save();app.innerHTML=`<div class="v3-shell page">${top()}<section class="celebration"><img src="assets/illustrations/tula-welcome.svg" alt="Tula"><span class="eyebrow">${t('ABENTEUER GESCHAFFT','AVENTURA COMPLETADA')}</span><h1>${t('Großartig gemacht!','¡Muy bien!')}</h1><p>${t(`Du hast ${game.score} von 6 Aufgaben gelöst.`,`Has resuelto ${game.score} de 6 preguntas.`)}</p><div class="reward-row"><div><span>✨</span><strong>+${game.score*10}</strong><small>XP</small></div><div><span>🐚</span><strong>+${bonus}</strong><small>${t('Muscheln','Conchas')}</small></div></div>${progress()}<button class="primary" data-action="home">⌂ ${t('Zur Startseite','Ir al inicio')}</button><button class="secondary" data-action="collection">${t('Weitere Übung','Otro ejercicio')}</button></section></div>`}
function renderLibrary(){state.collection='library';renderCollection()}
function simplePage(id,titleDe,titleEs,textDe,textEs){app.innerHTML=`<div class="v3-shell page">${top()}<section class="page-title"><span class="eyebrow">LINGUATURTLE 3.0</span><h1>${t(titleDe,titleEs)}</h1><p>${t(textDe,textEs)}</p></section><section class="panel"><img src="assets/illustrations/tula-welcome.svg" alt="Tula" style="width:180px;display:block;margin:auto"><h2 style="font-family:Georgia,serif;color:var(--navy);text-align:center">${t('Dieser Bereich wird als Nächstes ausgebaut.','Esta zona se ampliará a continuación.')}</h2></section></div>${nav(id)}`}
function renderLanguage(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="langModal"><section class="sheet"><span class="eyebrow">LANGUAGE / SPRACHE</span><h2>${t('App-Sprache wählen','Elegir idioma')}</h2><div class="language-card"><button class="${state.lang==='de'?'active':''}" data-lang="de">🇩🇪<br>Deutsch</button><button class="${state.lang==='es'?'active':''}" data-lang="es">🇪🇸<br>Español</button></div><br><button class="primary" data-action="close">${t('Schließen','Cerrar')}</button></section></div>`)}
function toast(text){document.querySelector('.v3-toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="v3-toast">${text}</div>`);setTimeout(()=>document.querySelector('.v3-toast')?.remove(),1600)}
function render(){({home:renderHome,island:renderIsland,library:renderLibrary,collection:renderCollection,explore:renderExplore,quiz:renderQuiz,shop:()=>simplePage('shop','Muschel-Boutique','Boutique de conchas','Booster, Tula-Outfits und neue Räume kommen hier hinein.','Aquí llegarán mejoras, ropa y nuevas salas.'),profile:()=>simplePage('profile','Dein Profil','Tu perfil','Level, Erfolge und Insel-Fortschritt werden hier sichtbar.','Aquí verás niveles, logros y progreso.') }[state.screen]||renderHome)()}
app.addEventListener('click',e=>{const screen=e.target.closest('[data-screen]')?.dataset.screen;const action=e.target.closest('[data-action]')?.dataset.action;const lang=e.target.closest('[data-lang]')?.dataset.lang;const place=e.target.closest('[data-place]')?.dataset.place;const mode=e.target.closest('[data-mode]')?.dataset.mode;const word=e.target.closest('[data-speak-word]')?.dataset.speakWord;const answerId=e.target.closest('[data-answer]')?.dataset.answer;if(screen){state.screen=screen;render();scrollTo({top:0,behavior:'smooth'})}if(place){state.collection=place;state.screen='collection';save();render()}if(mode==='explore'){state.screen='explore';render()}if(mode==='quiz'){state.screen='quiz';startQuiz()}if(word){const w=selectedCollection().words.find(x=>x.id===word);if(w)speak(w[target()])}if(answerId)answer(answerId);if(action==='language')renderLanguage();if(action==='close')document.querySelector('#langModal')?.remove();if(action==='repeat')speak(game.current[target()]);if(action==='home'){state.screen='home';render()}if(action==='collection'){state.screen='collection';render()}if(action==='back'){state.screen=state.screen==='collection'?'island':'collection';render()}if(lang){state.lang=lang;save();document.querySelector('#langModal')?.remove();render()}if(action==='menu')alert(t('Das Eltern- und Einstellungsmenü folgt im nächsten Schritt.','El menú de padres y ajustes llegará en el siguiente paso.'))});
render();