import {collections} from './content.js';

const KEY='linguaturtle-v3-preview';
const stored=JSON.parse(localStorage.getItem(KEY)||'{}');
const state={screen:'home',lang:stored.lang||'de',xp:Number(stored.xp||245),shells:Number(stored.shells||182),streak:Number(stored.streak||5),daily:Number(stored.daily||3),learned:stored.learned||{},collection:stored.collection||'garden',unlocked:stored.unlocked||[],boosters:stored.boosters||{doubleXp:0,hints:0,jumps:0},claimed:stored.claimed||[]};
const game={items:[],step:0,score:0,current:null,sentence:null,bank:[],built:[],reward:null};
const app=document.querySelector('#app');
const t=(de,es)=>state.lang==='de'?de:es;
const target=()=>state.lang==='de'?'es':'de';
const level=()=>Math.floor(state.xp/100)+1;
const xpInLevel=()=>state.xp%100;
const xpMissing=()=>100-xpInLevel();
const selectedCollection=()=>collections.find(c=>c.id===state.collection)||collections[0];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);

const shopItems=[
{id:'sentence',icon:'✒️',type:'mode',cost:80,de:'Satzwerkstatt',es:'Taller de frases',descDe:'Sätze bauen und Grammatik verstehen',descEs:'Construir frases y entender gramática'},
{id:'memory',icon:'🏛️',type:'mode',cost:120,de:'Palast-Memory',es:'Memoria del palacio',descDe:'Bild und Wort als Paare finden',descEs:'Encontrar parejas de imagen y palabra'},
{id:'speed',icon:'⏱️',type:'mode',cost:160,de:'Goldene Minute',es:'Minuto dorado',descDe:'Schnelle Fragen mit Combo-Bonus',descEs:'Preguntas rápidas con bonus combo'},
{id:'doubleXp',icon:'⚡',type:'booster',cost:60,de:'Doppel-XP',es:'XP doble',descDe:'Die nächsten 10 Aufgaben geben doppelte XP',descEs:'Las próximas 10 tareas dan XP doble'},
{id:'hint',icon:'💡',type:'booster',cost:25,de:'Hinweis-Booster',es:'Pista',descDe:'Zeigt in der Satzwerkstatt das nächste Wort',descEs:'Muestra la siguiente palabra en el taller'},
{id:'jump',icon:'🚀',type:'booster',cost:35,de:'Startsprung',es:'Salto inicial',descDe:'Eine schwierige Aufgabe überspringen',descEs:'Saltar una tarea difícil'}
];
const milestones=[
{level:3,icon:'📚',de:'Extra-Wörterpaket',es:'Paquete extra',detailDe:'+12 neue Wörter',detailEs:'+12 palabras nuevas',reward:{shells:30}},
{level:5,icon:'⚡',de:'Doppel-XP-Paket',es:'Paquete XP doble',detailDe:'10 Doppel-XP-Aufgaben',detailEs:'10 tareas con XP doble',reward:{doubleXp:10}},
{level:7,icon:'🐚',de:'Muschel-Schatz',es:'Tesoro de conchas',detailDe:'+100 Muscheln',detailEs:'+100 conchas',reward:{shells:100}},
{level:10,icon:'🚀',de:'Startsprünge',es:'Saltos iniciales',detailDe:'3 Aufgaben überspringen',detailEs:'Saltar 3 tareas',reward:{jumps:3}},
{level:15,icon:'⭐',de:'Sternen-Outfit',es:'Traje estelar',detailDe:'Exklusiver Tula-Look',detailEs:'Aspecto exclusivo de Tula',reward:{shells:150}},
{level:20,icon:'🎵',de:'Inselmusik',es:'Música de isla',detailDe:'Neue Klangwelt',detailEs:'Nuevo ambiente musical',reward:{shells:200}},
{level:30,icon:'🧰',de:'Legendäre Truhe',es:'Cofre legendario',detailDe:'500 Muscheln und Booster',detailEs:'500 conchas y mejoras',reward:{shells:500,doubleXp:20,hints:10,jumps:5}}
];
const sentences=[
{de:['Der','Hund','rennt','.'],es:['El','perro','corre','.']},
{de:['Die','Katze','schläft','.'],es:['El','gato','duerme','.']},
{de:['Ich','esse','einen','Apfel','.'],es:['Yo','como','una','manzana','.']},
{de:['Das','Wasser','ist','kalt','.'],es:['El','agua','está','fría','.']},
{de:['Wo','ist','mein','Buch','?'],es:['¿','Dónde','está','mi','libro','?']},
{de:['Die','Blume','ist','gelb','.'],es:['La','flor','es','amarilla','.']},
{de:['Der','Vogel','singt','im','Garten','.'],es:['El','pájaro','canta','en','el','jardín','.']}
];

function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function speak(text,lang=target()){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='de'?'de-DE':'es-ES';u.rate=.8;speechSynthesis.speak(u)}
function addReward(xp=0,shells=0){const doubled=state.boosters.doubleXp>0;if(doubled){xp*=2;state.boosters.doubleXp--}state.xp+=xp;state.shells+=shells;save();return{xp,shells}}
function top(back=false){return `<header class="v3-top"><button class="icon" data-action="${back?'back':'menu'}">${back?'←':'☰'}</button><div class="v3-brand"><i>🐢</i><strong>LinguaTurtle</strong></div><div class="top-actions"><button class="chip" data-action="language">${state.lang==='de'?'🇩🇪 DE':'🇪🇸 ES'}</button><span class="wallet-mini">🐚 ${state.shells}</span></div></header>`}
function nav(active){return `<nav class="v3-nav">${[['home','⌂',t('Home','Inicio')],['island','◉',t('Insel','Isla')],['library','▤',t('Wörter','Palabras')],['shop','♛',t('Shop','Tienda')],['profile','♙',t('Profil','Perfil')]].map(([id,icon,label])=>`<button class="${active===id?'active':''}" data-screen="${id}"><span>${icon}</span><small>${label}</small></button>`).join('')}</nav>`}
function progress(){return `<section class="progress-card"><div class="progress-head"><strong>${t('Level','Nivel')} ${level()}</strong><span>${t(`Noch ${xpMissing()} XP bis Level ${level()+1}`,`Faltan ${xpMissing()} XP para nivel ${level()+1}`)}</span></div><div class="bar"><i style="width:${xpInLevel()}%"></i></div></section>`}
function renderHome(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="hero-v3"><div class="hero-copy"><span class="eyebrow">TURTLE ISLAND</span><h1>${t('Komm mit auf die Insel!','¡Ven a la isla!')}</h1><p>${t('Tula wartet auf dein nächstes Sprachabenteuer.','Tula espera tu próxima aventura lingüística.')}</p><button class="chip" data-screen="island">${t('Insel entdecken','Descubrir la isla')} →</button></div><img class="tula-art" src="assets/illustrations/tula-welcome.svg" alt="Tula"></section><section class="stats-v3"><div><span>✨</span><strong>${state.xp}</strong><small>XP</small></div><div><span>🐚</span><strong>${state.shells}</strong><small>${t('Muscheln','Conchas')}</small></div><div><span>🔥</span><strong>${state.streak}</strong><small>${t('Lerntage','Días')}</small></div></section>${progress()}<div class="section-head"><div><span class="eyebrow">${t('HEUTE','HOY')}</span><h2>${t('Dein nächstes Abenteuer','Tu próxima aventura')}</h2></div></div><section class="journey-grid">${collections.map(c=>`<button data-place="${c.id}"><span>${c.icon}</span><div><strong>${c[state.lang]}</strong><small>${state.learned[c.id]||0}/${c.words.length} ${t('Wörter entdeckt','palabras descubiertas')}</small></div><b>→</b></button>`).join('')}</section><button class="island-card" data-screen="island"><img src="assets/illustrations/turtle-island.svg" alt="Turtle Island"><span class="island-info"><span><strong>${t('Deine Lerninsel','Tu isla de aprendizaje')}</strong><small>${t('Bibliothek, Garten und Boutique sind geöffnet','Biblioteca, jardín y tienda abiertos')}</small></span><b>→</b></span></button></div>${nav('home')}`}
function renderIsland(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="page-title"><span class="eyebrow">TURTLE ISLAND</span><h1>${t('Wohin möchtest du?','¿Adónde quieres ir?')}</h1><p>${t('Jeder Ort öffnet einen anderen Teil deiner Sprachreise.','Cada lugar abre una parte distinta de tu viaje.')}</p></section><button class="island-card"><img src="assets/illustrations/turtle-island.svg" alt="Turtle Island"></button><div class="section-head"><div><span class="eyebrow">${t('ORTE','LUGARES')}</span><h2>${t('Wähle ein Abenteuer','Elige una aventura')}</h2></div></div><section class="places">${collections.map(c=>`<button class="place" data-place="${c.id}"><span>${c.icon}</span><strong>${c[state.lang]}</strong><small>${c[state.lang==='de'?'subtitleDe':'subtitleEs']}</small></button>`).join('')}<button class="place" data-screen="shop"><span>🏪</span><strong>${t('Boutique','Boutique')}</strong><small>${t('Modi & Booster','Modos y mejoras')}</small></button><button class="place ${level()<10?'locked':''}" ${level()>=10?'data-mode="sentence"':''}><span>🏰</span><strong>${t('Schloss','Castillo')}</strong><small>${level()>=10?t('Satzwerkstatt','Taller de frases'):t('Ab Level 10','Desde nivel 10')}</small></button></section></div>${nav('island')}`}
function renderCollection(){const c=selectedCollection();const sentenceOpen=state.unlocked.includes('sentence');app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="place-hero"><span>${c.icon}</span><div><span class="eyebrow">${c.id==='garden'?t('TULAS GARTEN','EL JARDÍN DE TULA'):t('INSELBIBLIOTHEK','BIBLIOTECA DE LA ISLA')}</span><h1>${c[state.lang]}</h1><p>${c[state.lang==='de'?'subtitleDe':'subtitleEs']}</p></div></section><section class="mode-picker"><button data-mode="explore"><span>👀</span><div><strong>${t('Wörter entdecken','Descubrir palabras')}</strong><small>${t('Belohnung: 🐚 6 + XP','Recompensa: 🐚 6 + XP')}</small></div><b>→</b></button><button data-mode="quiz"><span>🎧</span><div><strong>${t('Hör-Abenteuer','Aventura auditiva')}</strong><small>${t('Belohnung: bis zu 🐚 18','Recompensa: hasta 🐚 18')}</small></div><b>→</b></button><button data-mode="sentence" class="${sentenceOpen?'':'locked'}"><span>✒️</span><div><strong>${t('Satzwerkstatt','Taller de frases')}</strong><small>${sentenceOpen?t('Belohnung: bis zu 🐚 25','Recompensa: hasta 🐚 25'):t('In der Boutique freischalten','Desbloquear en la boutique')}</small></div><b>${sentenceOpen?'→':'🔒'}</b></button></section><div class="word-showcase">${c.words.slice(0,8).map(w=>`<article><span>${w.emoji}</span><strong>${w[state.lang]}</strong><small>${w[target()]}</small></article>`).join('')}</div></div>${nav(c.id==='library'?'library':'island')}`}
function renderExplore(){const c=selectedCollection();app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="page-title"><span class="eyebrow">${t('WÖRTER ENTDECKEN','DESCUBRIR PALABRAS')}</span><h1>${c[state.lang]}</h1><p>${t('Tippe eine Karte an, um das Wort zu hören.','Toca una tarjeta para escuchar la palabra.')}</p></section><div class="explore-grid">${c.words.map(w=>`<button data-speak-word="${w.id}"><span>${w.emoji}</span><strong>${w[target()]}</strong><small>${w[state.lang]}</small><em>🔊</em></button>`).join('')}</div><button class="primary" data-action="finish-explore">${t('Lernrunde abschließen · 🐚 6','Terminar ronda · 🐚 6')}</button></div>${nav(c.id==='library'?'library':'island')}`}
function startQuiz(){game.items=shuffle(selectedCollection().words).slice(0,6);game.step=0;game.score=0;renderQuiz()}
function renderQuiz(){if(game.step>=game.items.length)return finishQuiz();const c=selectedCollection(),cur=game.items[game.step];game.current=cur;const opts=shuffle([cur,...shuffle(c.words.filter(w=>w.id!==cur.id)).slice(0,3)]);app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="quiz-head"><div class="bar"><i style="width:${game.step/game.items.length*100}%"></i></div><span>${game.step+1}/${game.items.length}</span></section><section class="listen-card"><span>🎧</span><h2>${t('Hör gut zu','Escucha con atención')}</h2><p>${t('Welches Bild gehört zum Wort?','¿Qué imagen corresponde?')}</p><button data-action="repeat">🔊 ${t('Noch einmal','Otra vez')}</button></section><div class="quiz-grid">${opts.map(w=>`<button data-answer="${w.id}"><span>${w.emoji}</span><strong>${w[state.lang]}</strong></button>`).join('')}</div></div>`;setTimeout(()=>speak(cur[target()]),250)}
function answer(id){if(id!==game.current.id){toast(t('Fast! Versuch es noch einmal.','¡Casi! Inténtalo otra vez.'));return}game.score++;game.step++;addReward(10,2);state.daily=Math.min(5,state.daily+1);state.learned[state.collection]=Math.max(state.learned[state.collection]||0,game.step);save();toast(t('Sehr gut! +2 Muscheln','¡Muy bien! +2 conchas'));setTimeout(renderQuiz,450)}
function finishQuiz(){game.reward=addReward(15,6);renderComplete(t('Hör-Abenteuer geschafft!','¡Aventura auditiva completada!'),game.score*10+game.reward.xp,game.score*2+game.reward.shells)}
function finishExplore(){const c=selectedCollection();state.learned[c.id]=c.words.length;game.reward=addReward(20,6);save();renderComplete(t('Wörter entdeckt!','¡Palabras descubiertas!'),game.reward.xp,game.reward.shells)}
function startSentence(){if(!state.unlocked.includes('sentence')){state.screen='shop';return render()}game.step=0;game.score=0;nextSentence()}
function nextSentence(){if(game.step>=5)return finishSentence();game.sentence=sentences[(game.step+Math.floor(Math.random()*sentences.length))%sentences.length];game.built=[];game.bank=shuffle(game.sentence[target()].map((text,i)=>({id:`${game.step}-${i}-${text}`,text})));state.screen='sentence';renderSentence()}
function tile(x){return `<button class="sentence-tile" data-tile="${x.id}"><span>⠿</span>${x.text}</button>`}
function renderSentence(){const src=game.sentence[state.lang].join(' ');app.innerHTML=`<div class="v3-shell page">${top(true)}<section class="sentence-guide-v3"><img src="assets/illustrations/tula-welcome.svg" alt="Tula"><div><span class="eyebrow">${t('SATZWERKSTATT','TALLER DE FRASES')}</span><h1>${t('Baue den Satz','Construye la frase')}</h1><p>${t('Ziehe oder tippe die Wörter in die richtige Reihenfolge.','Arrastra o toca las palabras en el orden correcto.')}</p></div></section><section class="sentence-example"><span>${state.lang==='de'?'🇩🇪':'🇪🇸'}</span><div><small>${t('DEINE VORLAGE','TU EJEMPLO')}</small><strong>${src}</strong></div><button data-action="speak-source">🔊</button></section><section class="sentence-zone" data-zone="built">${game.built.length?game.built.map(tile).join(''):`<div class="sentence-empty"><b>↓</b><strong>${t('Baue deinen Satz hier','Construye tu frase aquí')}</strong><small>${t('Die Karten rasten automatisch ein.','Las tarjetas encajan automáticamente.')}</small></div>`}</section><section class="sentence-bank" data-zone="bank">${game.bank.map(tile).join('')}</section><div class="sentence-tools"><button data-action="sentence-reset">↺ ${t('Neu mischen','Mezclar')}</button>${state.boosters.hints>0?`<button data-action="hint">💡 ${t('Hinweis','Pista')} (${state.boosters.hints})</button>`:''}</div><button class="primary" data-action="sentence-check" ${game.bank.length?'disabled':''}>${t('Satz prüfen','Comprobar frase')} ✓</button></div>`;enableSentenceDrag()}
function moveSentenceTile(id,to,index=null){let tileObj;let i=game.bank.findIndex(x=>x.id===id);if(i>=0)tileObj=game.bank.splice(i,1)[0];else{i=game.built.findIndex(x=>x.id===id);if(i>=0)tileObj=game.built.splice(i,1)[0]}if(!tileObj)return;const list=to==='built'?game.built:game.bank;if(index===null||index>list.length)list.push(tileObj);else list.splice(index,0,tileObj);renderSentence()}
function enableSentenceDrag(){document.querySelectorAll('.sentence-tile').forEach(el=>{el.addEventListener('click',()=>moveSentenceTile(el.dataset.tile,el.closest('[data-zone]').dataset.zone==='built'?'bank':'built'));el.draggable=true;el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',el.dataset.tile))});document.querySelectorAll('[data-zone]').forEach(zone=>{zone.addEventListener('dragover',e=>e.preventDefault());zone.addEventListener('drop',e=>{e.preventDefault();moveSentenceTile(e.dataTransfer.getData('text/plain'),zone.dataset.zone)})})}
function checkSentence(){const expected=game.sentence[target()];const actual=game.built.map(x=>x.text);if(JSON.stringify(expected)!==JSON.stringify(actual)){toast(t('Noch nicht ganz – ordne die Karten neu.','Aún no. Reordena las tarjetas.'));return}game.score++;addReward(18,4);speak(expected.join(' '));toast(t('Perfekt gebaut! +4 Muscheln','¡Perfecto! +4 conchas'));setTimeout(()=>{game.step++;nextSentence()},700)}
function hintSentence(){if(!state.boosters.hints)return;const expected=game.sentence[target()];const position=game.built.length;const wanted=expected[position];const item=game.bank.find(x=>x.text===wanted);if(item){state.boosters.hints--;save();moveSentenceTile(item.id,'built');toast(t('Das nächste Wort wurde eingesetzt.','Se colocó la siguiente palabra.'))}}
function finishSentence(){game.reward=addReward(20,5);renderComplete(t('Satzwerkstatt geschafft!','¡Taller de frases completado!'),game.score*18+game.reward.xp,game.score*4+game.reward.shells)}
function renderComplete(title,xp,shells){app.innerHTML=`<div class="v3-shell page">${top()}<section class="celebration"><img src="assets/illustrations/tula-welcome.svg" alt="Tula"><span class="eyebrow">${t('ABENTEUER GESCHAFFT','AVENTURA COMPLETADA')}</span><h1>${title}</h1><p>${t('Tula ist stolz auf dich.','Tula está orgullosa de ti.')}</p><div class="reward-row"><div><span>✨</span><strong>+${xp}</strong><small>XP</small></div><div><span>🐚</span><strong>+${shells}</strong><small>${t('Muscheln','Conchas')}</small></div></div>${progress()}<button class="primary" data-action="home">⌂ ${t('Zur Startseite','Ir al inicio')}</button><button class="secondary" data-action="collection">${t('Weitere Übung','Otro ejercicio')}</button></section></div>`}
function renderShop(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="shop-hero-v3"><span>♛</span><div><span class="eyebrow">${t('MUSCHEL-BOUTIQUE','BOUTIQUE DE CONCHAS')}</span><h1>${t('Besondere Schätze','Tesoros especiales')}</h1><p>${t('Alles wird erspielt – keine echten Käufe.','Todo se gana jugando; no hay compras reales.')}</p></div></section><section class="wallet-card"><span>🐚</span><div><strong>${state.shells}</strong><small>${t('verfügbare Muscheln','conchas disponibles')}</small></div></section><div class="shop-section"><h2>${t('Spielmodi','Modos de juego')}</h2>${shopItems.filter(x=>x.type==='mode').map(shopCard).join('')}<h2>Booster</h2>${shopItems.filter(x=>x.type==='booster').map(shopCard).join('')}</div></div>${nav('shop')}`}
function shopCard(item){const owned=item.type==='mode'&&state.unlocked.includes(item.id);const count=item.type==='booster'?state.boosters[item.id]||0:0;return `<article class="shop-card-v3 ${owned?'owned':''}"><span>${item.icon}</span><div><strong>${item[state.lang]}</strong><small>${item[state.lang==='de'?'descDe':'descEs']}</small>${count?`<em>${t('Vorrat','Inventario')}: ${count}</em>`:''}</div><button data-buy="${item.id}" ${owned?'disabled':''}>${owned?'✓':`🐚 ${item.cost}`}</button></article>`}
function buyItem(id){const item=shopItems.find(x=>x.id===id);if(!item||state.shells<item.cost){toast(t('Noch nicht genug Muscheln.','Aún no tienes suficientes conchas.'));return}if(item.type==='mode'&&state.unlocked.includes(id))return;state.shells-=item.cost;if(item.type==='mode')state.unlocked.push(id);else state.boosters[id]=(state.boosters[id]||0)+(id==='doubleXp'?10:1);save();toast(t('Freigeschaltet!','¡Desbloqueado!'));renderShop()}
function renderProfile(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="profile-hero-v3"><img src="assets/illustrations/tula-welcome.svg" alt="Tula"><span class="eyebrow">${t('DEIN FORTSCHRITT','TU PROGRESO')}</span><h1>${t('Inselentdecker','Explorador de la isla')}</h1><strong>${t('Level','Nivel')} ${level()} · ${state.xp} XP</strong></section>${progress()}<section class="profile-stats"><div><span>🔥</span><strong>${state.streak}</strong><small>${t('Lerntage','Días')}</small></div><div><span>🐚</span><strong>${state.shells}</strong><small>${t('Muscheln','Conchas')}</small></div><div><span>📚</span><strong>${Object.values(state.learned).reduce((a,b)=>a+Number(b||0),0)}</strong><small>${t('entdeckt','descubiertas')}</small></div></section><section class="daily-card"><div><span>☀️</span><div><strong>${t('Tagesziel','Meta diaria')}</strong><small>${state.daily}/5 ${t('Aufgaben geschafft','tareas completadas')}</small></div></div><div class="daily-dots">${[0,1,2,3,4].map(i=>`<i class="${i<state.daily?'on':''}"></i>`).join('')}</div></section><section class="milestone-list"><div class="section-head"><div><span class="eyebrow">${t('LEVEL-BELOHNUNGEN','RECOMPENSAS')}</span><h2>${t('Deine nächsten Schätze','Tus próximos tesoros')}</h2></div></div>${milestones.map(m=>milestoneCard(m)).join('')}</section></div>${nav('profile')}`}
function milestoneCard(m){const reached=level()>=m.level,claimed=state.claimed.includes(m.level);return `<article class="milestone-card ${reached?'reached':''}"><span>${m.icon}</span><div><small>LEVEL ${m.level}</small><strong>${m[state.lang]}</strong><em>${m[state.lang==='de'?'detailDe':'detailEs']}</em></div>${claimed?'<b>✓</b>':reached?`<button data-claim="${m.level}">${t('Abholen','Recoger')}</button>`:'<b>🔒</b>'}</article>`}
function claimMilestone(lv){const m=milestones.find(x=>x.level===lv);if(!m||level()<lv||state.claimed.includes(lv))return;state.claimed.push(lv);state.shells+=m.reward.shells||0;state.boosters.doubleXp+=(m.reward.doubleXp||0);state.boosters.hints+=(m.reward.hints||0);state.boosters.jumps+=(m.reward.jumps||0);save();toast(t('Belohnung eingesammelt!','¡Recompensa recogida!'));renderProfile()}
function renderLibrary(){state.collection='library';renderCollection()}
function renderLanguage(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="langModal"><section class="sheet"><span class="eyebrow">LANGUAGE / SPRACHE</span><h2>${t('App-Sprache wählen','Elegir idioma')}</h2><div class="language-card"><button class="${state.lang==='de'?'active':''}" data-lang="de">🇩🇪<br>Deutsch</button><button class="${state.lang==='es'?'active':''}" data-lang="es">🇪🇸<br>Español</button></div><br><button class="primary" data-action="close">${t('Schließen','Cerrar')}</button></section></div>`)}
function toast(text){document.querySelector('.v3-toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="v3-toast">${text}</div>`);setTimeout(()=>document.querySelector('.v3-toast')?.remove(),1600)}
function render(){({home:renderHome,island:renderIsland,library:renderLibrary,collection:renderCollection,explore:renderExplore,quiz:renderQuiz,sentence:renderSentence,shop:renderShop,profile:renderProfile}[state.screen]||renderHome)()}
app.addEventListener('click',e=>{const screen=e.target.closest('[data-screen]')?.dataset.screen;const action=e.target.closest('[data-action]')?.dataset.action;const lang=e.target.closest('[data-lang]')?.dataset.lang;const place=e.target.closest('[data-place]')?.dataset.place;const mode=e.target.closest('[data-mode]')?.dataset.mode;const word=e.target.closest('[data-speak-word]')?.dataset.speakWord;const answerId=e.target.closest('[data-answer]')?.dataset.answer;const buy=e.target.closest('[data-buy]')?.dataset.buy;const claim=e.target.closest('[data-claim]')?.dataset.claim;if(screen){state.screen=screen;render();scrollTo({top:0,behavior:'smooth'})}if(place){state.collection=place;state.screen='collection';save();render()}if(mode==='explore'){state.screen='explore';render()}if(mode==='quiz'){state.screen='quiz';startQuiz()}if(mode==='sentence')startSentence();if(word){const w=selectedCollection().words.find(x=>x.id===word);if(w)speak(w[target()])}if(answerId)answer(answerId);if(buy)buyItem(buy);if(claim)claimMilestone(Number(claim));if(action==='language')renderLanguage();if(action==='close')document.querySelector('#langModal')?.remove();if(action==='repeat')speak(game.current[target()]);if(action==='home'){state.screen='home';render()}if(action==='collection'){state.screen='collection';render()}if(action==='finish-explore')finishExplore();if(action==='sentence-reset')nextSentence();if(action==='sentence-check')checkSentence();if(action==='speak-source')speak(game.sentence[state.lang].join(' '),state.lang);if(action==='hint')hintSentence();if(action==='back'){state.screen=['explore','quiz','sentence'].includes(state.screen)?'collection':'island';render()}if(lang){state.lang=lang;save();document.querySelector('#langModal')?.remove();render()}if(action==='menu')alert(t('Elternbereich und Einstellungen folgen im nächsten Ausbau.','La zona de padres y los ajustes llegarán después.'))});
render();