const KEY='linguaturtle-v3-preview';
const stored=JSON.parse(localStorage.getItem(KEY)||'{}');
const state={screen:'home',lang:stored.lang||'de',xp:stored.xp||245,shells:stored.shells||182,streak:stored.streak||5,level:stored.level||5,daily:stored.daily||3};
const app=document.querySelector('#app');
const t=(de,es)=>state.lang==='de'?de:es;
const xpInLevel=()=>state.xp%100;
const xpMissing=()=>100-xpInLevel();
function save(){localStorage.setItem(KEY,JSON.stringify({lang:state.lang,xp:state.xp,shells:state.shells,streak:state.streak,level:state.level,daily:state.daily}))}
function top(){return `<header class="v3-top"><button class="icon" data-action="menu">☰</button><div class="v3-brand"><i>🐢</i><strong>LinguaTurtle</strong></div><button class="chip" data-action="language">${state.lang==='de'?'🇩🇪 DE':'🇪🇸 ES'}</button></header>`}
function nav(active){return `<nav class="v3-nav">${[['home','⌂',t('Home','Inicio')],['island','◉',t('Insel','Isla')],['library','▤',t('Wörter','Palabras')],['shop','♛',t('Shop','Tienda')],['profile','♙',t('Profil','Perfil')]].map(([id,icon,label])=>`<button class="${active===id?'active':''}" data-screen="${id}"><span>${icon}</span><small>${label}</small></button>`).join('')}</nav>`}
function progress(){return `<section class="progress-card"><div class="progress-head"><strong>${t('Level','Nivel')} ${state.level}</strong><span>${t(`Noch ${xpMissing()} XP bis Level ${state.level+1}`,`Faltan ${xpMissing()} XP para nivel ${state.level+1}`)}</span></div><div class="bar"><i style="width:${xpInLevel()}%"></i></div></section>`}
function renderHome(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="hero-v3"><div class="hero-copy"><span class="eyebrow">TURTLE ISLAND</span><h1>${t('Komm mit auf die Insel!','¡Ven a la isla!')}</h1><p>${t('Tula wartet auf dein nächstes Sprachabenteuer.','Tula espera tu próxima aventura lingüística.')}</p><button class="chip" data-screen="island">${t('Insel entdecken','Descubrir la isla')} →</button></div><img class="tula-art" src="assets/illustrations/tula-welcome.svg" alt="Tula die Schildkröte"></section><section class="stats-v3"><div><span>✨</span><strong>${state.xp}</strong><small>XP</small></div><div><span>🐚</span><strong>${state.shells}</strong><small>${t('Muscheln','Conchas')}</small></div><div><span>🔥</span><strong>${state.streak}</strong><small>${t('Lerntage','Días')}</small></div></section>${progress()}<div class="section-head"><div><span class="eyebrow">${t('DEINE WELT','TU MUNDO')}</span><h2>${t('Turtle Island','Isla Tortuga')}</h2></div></div><button class="island-card" data-screen="island"><img src="assets/illustrations/turtle-island.svg" alt="Karte von Turtle Island"><span class="island-info"><span><strong>${t('Deine Lerninsel','Tu isla de aprendizaje')}</strong><small>${t('5 Orte · 3 bald verfügbar','5 lugares · 3 muy pronto')}</small></span><b>→</b></span></button></div>${nav('home')}`}
function renderIsland(){app.innerHTML=`<div class="v3-shell page">${top()}<section class="page-title"><span class="eyebrow">TURTLE ISLAND</span><h1>${t('Wohin möchtest du?','¿Adónde quieres ir?')}</h1><p>${t('Jeder Ort öffnet einen anderen Teil deiner Sprachreise.','Cada lugar abre una parte distinta de tu viaje.')}</p></section><button class="island-card"><img src="assets/illustrations/turtle-island.svg" alt="Turtle Island"></button><div class="section-head"><div><span class="eyebrow">${t('ORTE','LUGARES')}</span><h2>${t('Wähle ein Abenteuer','Elige una aventura')}</h2></div></div><section class="places"><button class="place"><span>📚</span><strong>${t('Bibliothek','Biblioteca')}</strong><small>${t('Wörter & Sätze','Palabras y frases')}</small></button><button class="place"><span>🌿</span><strong>${t('Garten','Jardín')}</strong><small>${t('Essen & Natur','Comida y naturaleza')}</small></button><button class="place locked"><span>⚓</span><strong>${t('Hafen','Puerto')}</strong><small>${t('Ab Level 7','Desde nivel 7')}</small></button><button class="place locked"><span>🏰</span><strong>${t('Schloss','Castillo')}</strong><small>${t('Ab Level 10','Desde nivel 10')}</small></button></section></div>${nav('island')}`}
function simplePage(id,titleDe,titleEs,textDe,textEs){app.innerHTML=`<div class="v3-shell page">${top()}<section class="page-title"><span class="eyebrow">LINGUATURTLE 3.0</span><h1>${t(titleDe,titleEs)}</h1><p>${t(textDe,textEs)}</p></section><section class="panel"><img src="assets/illustrations/tula-welcome.svg" alt="Tula" style="width:180px;display:block;margin:auto"><h2 style="font-family:Georgia,serif;color:var(--navy);text-align:center">${t('Dieser Bereich wird als Nächstes ausgebaut.','Esta zona se ampliará a continuación.')}</h2></section></div>${nav(id)}`}
function renderLanguage(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="langModal"><section class="sheet"><span class="eyebrow">LANGUAGE / SPRACHE</span><h2>${t('App-Sprache wählen','Elegir idioma')}</h2><div class="language-card"><button class="${state.lang==='de'?'active':''}" data-lang="de">🇩🇪<br>Deutsch</button><button class="${state.lang==='es'?'active':''}" data-lang="es">🇪🇸<br>Español</button></div><br><button class="primary" data-action="close">${t('Schließen','Cerrar')}</button></section></div>`)}
function render(){({home:renderHome,island:renderIsland,library:()=>simplePage('library','Wörterbibliothek','Biblioteca','Dein Wortschatz wächst bald in illustrierten Sammlungen.','Tu vocabulario crecerá en colecciones ilustradas.'),shop:()=>simplePage('shop','Muschel-Boutique','Boutique de conchas','Booster, Tula-Outfits und neue Räume kommen hier hinein.','Aquí llegarán mejoras, ropa y nuevas salas.'),profile:()=>simplePage('profile','Dein Profil','Tu perfil','Level, Erfolge und Insel-Fortschritt werden hier sichtbar.','Aquí verás niveles, logros y progreso.') }[state.screen]||renderHome)()}
app.addEventListener('click',e=>{const screen=e.target.closest('[data-screen]')?.dataset.screen;const action=e.target.closest('[data-action]')?.dataset.action;const lang=e.target.closest('[data-lang]')?.dataset.lang;if(screen){state.screen=screen;render();scrollTo({top:0,behavior:'smooth'})}if(action==='language')renderLanguage();if(action==='close')document.querySelector('#langModal')?.remove();if(lang){state.lang=lang;save();document.querySelector('#langModal')?.remove();render()}if(action==='menu')alert(t('Das Eltern- und Einstellungsmenü folgt im nächsten Schritt.','El menú de padres y ajustes llegará en el siguiente paso.'))});
render();