export const collections=[
{id:'garden',icon:'🌿',de:'Garten',es:'Jardín',subtitleDe:'Obst, Gemüse und Natur',subtitleEs:'Frutas, verduras y naturaleza',words:[
['apple','🍎','Apfel','manzana'],['pear','🍐','Birne','pera'],['banana','🍌','Banane','plátano'],['strawberry','🍓','Erdbeere','fresa'],['grapes','🍇','Trauben','uvas'],['carrot','🥕','Karotte','zanahoria'],['tomato','🍅','Tomate','tomate'],['cucumber','🥒','Gurke','pepino'],['lemon','🍋','Zitrone','limón'],['orange','🍊','Orange','naranja'],['flower','🌸','Blume','flor'],['tree','🌳','Baum','árbol'],['potato','🥔','Kartoffel','patata'],['onion','🧅','Zwiebel','cebolla'],['pepper','🫑','Paprika','pimiento'],['watermelon','🍉','Wassermelone','sandía'],['cherries','🍒','Kirschen','cerezas'],['mushroom','🍄','Pilz','seta']]},
{id:'library',icon:'📚',de:'Bibliothek',es:'Biblioteca',subtitleDe:'Schule, Bücher und erste Sätze',subtitleEs:'Escuela, libros y primeras frases',words:[
['book','📘','Buch','libro'],['pen','✏️','Stift','lápiz'],['chair','🪑','Stuhl','silla'],['table','🪵','Tisch','mesa'],['lamp','💡','Lampe','lámpara'],['door','🚪','Tür','puerta'],['window','🪟','Fenster','ventana'],['clock','🕰️','Uhr','reloj'],['letter','✉️','Brief','carta'],['picture','🖼️','Bild','imagen'],['school','🏫','Schule','escuela'],['teacher','🧑‍🏫','Lehrer','profesor'],['pencilcase','🖍️','Mäppchen','estuche'],['paper','📄','Papier','papel'],['scissors','✂️','Schere','tijeras'],['backpack','🎒','Rucksack','mochila'],['notebook','📓','Heft','cuaderno'],['ruler','📏','Lineal','regla']]},
{id:'animals',icon:'🐾',de:'Tierwelt',es:'Mundo animal',subtitleDe:'Haustiere, Wald und Bauernhof',subtitleEs:'Mascotas, bosque y granja',words:[
['dog','🐶','Hund','perro'],['cat','🐱','Katze','gato'],['bird','🐦','Vogel','pájaro'],['fish','🐟','Fisch','pez'],['horse','🐴','Pferd','caballo'],['cow','🐮','Kuh','vaca'],['pig','🐷','Schwein','cerdo'],['rabbit','🐰','Kaninchen','conejo'],['lion','🦁','Löwe','león'],['elephant','🐘','Elefant','elefante'],['bear','🐻','Bär','oso'],['fox','🦊','Fuchs','zorro'],['frog','🐸','Frosch','rana'],['turtle','🐢','Schildkröte','tortuga'],['bee','🐝','Biene','abeja'],['butterfly','🦋','Schmetterling','mariposa'],['duck','🦆','Ente','pato'],['sheep','🐑','Schaf','oveja']]},
{id:'home',icon:'🏡',de:'Zuhause',es:'Casa',subtitleDe:'Zimmer, Möbel und Alltag',subtitleEs:'Habitaciones, muebles y vida diaria',words:[
['bed','🛏️','Bett','cama'],['sofa','🛋️','Sofa','sofá'],['key','🔑','Schlüssel','llave'],['mirror','🪞','Spiegel','espejo'],['bathtub','🛁','Badewanne','bañera'],['broom','🧹','Besen','escoba'],['basket','🧺','Korb','cesta'],['plant','🪴','Pflanze','planta'],['pillow','🛌','Kissen','almohada'],['blanket','🧣','Decke','manta'],['kitchen','🍳','Küche','cocina'],['bathroom','🚿','Badezimmer','baño'],['gardenhome','🏡','Garten','jardín'],['fridge','🧊','Kühlschrank','nevera'],['plate','🍽️','Teller','plato'],['cup','🥛','Becher','vaso'],['spoon','🥄','Löffel','cuchara'],['fork','🍴','Gabel','tenedor']]},
{id:'family',icon:'👨‍👩‍👧',de:'Familie',es:'Familia',subtitleDe:'Menschen und Beziehungen',subtitleEs:'Personas y relaciones',words:[
['mother','👩','Mutter','madre'],['father','👨','Vater','padre'],['sister','👧','Schwester','hermana'],['brother','👦','Bruder','hermano'],['grandmother','👵','Großmutter','abuela'],['grandfather','👴','Großvater','abuelo'],['baby','👶','Baby','bebé'],['familyword','👨‍👩‍👧','Familie','familia'],['friend','🧒','Freund','amigo'],['girl','👧','Mädchen','niña'],['boy','👦','Junge','niño'],['woman','👩‍🦰','Frau','mujer'],['man','👨‍🦰','Mann','hombre'],['child','🧒','Kind','niño'],['aunt','👩','Tante','tía'],['uncle','👨','Onkel','tío']]},
{id:'body',icon:'🖐️',de:'Körper',es:'Cuerpo',subtitleDe:'Körperteile und Gefühle',subtitleEs:'Partes del cuerpo y emociones',words:[
['eye','👁️','Auge','ojo'],['ear','👂','Ohr','oreja'],['nose','👃','Nase','nariz'],['mouth','👄','Mund','boca'],['tooth','🦷','Zahn','diente'],['hand','🖐️','Hand','mano'],['foot','🦶','Fuß','pie'],['leg','🦵','Bein','pierna'],['arm','💪','Arm','brazo'],['heart','❤️','Herz','corazón'],['head','🙂','Kopf','cabeza'],['hair','💇','Haare','pelo'],['happy','😊','fröhlich','feliz'],['sad','😢','traurig','triste'],['tired','🥱','müde','cansado'],['angry','😠','wütend','enfadado'],['afraid','😨','ängstlich','asustado'],['hungry','😋','hungrig','hambriento']]},
{id:'travel',icon:'⚓',de:'Unterwegs',es:'De viaje',subtitleDe:'Fahrzeuge, Orte und Reisen',subtitleEs:'Vehículos, lugares y viajes',words:[
['car','🚗','Auto','coche'],['bus','🚌','Bus','autobús'],['train','🚆','Zug','tren'],['ship','🚢','Schiff','barco'],['airplane','✈️','Flugzeug','avión'],['bicycle','🚲','Fahrrad','bicicleta'],['station','🚉','Bahnhof','estación'],['airport','🛫','Flughafen','aeropuerto'],['ticket','🎫','Fahrkarte','billete'],['suitcase','🧳','Koffer','maleta'],['hotel','🏨','Hotel','hotel'],['street','🛣️','Straße','calle'],['bridge','🌉','Brücke','puente'],['city','🏙️','Stadt','ciudad'],['village','🏘️','Dorf','pueblo'],['map','🗺️','Karte','mapa']]},
{id:'actions',icon:'🏃',de:'Bewegung',es:'Acciones',subtitleDe:'Wichtige Verben im Alltag',subtitleEs:'Verbos importantes del día a día',words:[
['run','🏃','laufen','correr'],['walk','🚶','gehen','caminar'],['sleep','😴','schlafen','dormir'],['eat','🍽️','essen','comer'],['drink','🥤','trinken','beber'],['read','📖','lesen','leer'],['write','✍️','schreiben','escribir'],['sing','🎵','singen','cantar'],['dance','💃','tanzen','bailar'],['paint','🎨','malen','pintar'],['play','⚽','spielen','jugar'],['listen','👂','hören','escuchar'],['speak','🗣️','sprechen','hablar'],['open','📂','öffnen','abrir'],['close','📕','schließen','cerrar'],['help','🤝','helfen','ayudar'],['laugh','😂','lachen','reír'],['learn','🧠','lernen','aprender']]}
].map(collection=>({...collection,words:collection.words.map(([id,emoji,de,es])=>({id:`${collection.id}-${id}`,emoji,de,es}))}));

export const allWords=collections.flatMap(collection=>collection.words.map(word=>({...word,collection:collection.id})));
