import { collections } from './content.js';
import { createRouter,registerAction,bindActions,getState,setState,migrateLegacyState,levelFromXp,levelProgress } from './core/index.js';
import { registerLearningRoutes,registerLearningActions } from './games/core-learning.js';
import { registerAdvancedRoutes,registerAdvancedActions } from './games/advanced.js';
import { registerExperienceRoutes,registerExperienceActions } from './games/experiences.js';
import { renderShop,renderProfile,renderSettings,registerProgressionActions } from './screens/progression.js';
import { renderChildProfile,registerChildProfileActions } from './screens/child-profile.js';

const app=document.querySelector('#app');
const router=createRouter(app);
migrateLegacyState();
const tr=(de,es)=>getState().language==='es'?es:de;
const currentCollection=()=>collections.find(c=>c.id===getState().session.collectionId)||collections[0];
function top(backRoute=null){const s=getState();return `<header class="v3-top"><button class="icon" data-action="${backRoute?'navigate':'menu'}" ${backRoute?`data-route="${backRoute}"`:''}>${backRoute?'←':'☰'}</button><div class="v3-brand"><i>🐢</i><strong>LinguaTurtle</strong></div><div class="top-actions"><button class="chip" data-action="toggle-language">${s.language==='de'?'🇩🇪 DE':'🇪🇸 ES'}</button><span class="wallet-mini">🐚 ${s.progress.shells}</span></div></header>`}
function nav(active){return `<nav class="v3-nav">${[['home','⌂',tr('Home','Inicio')],['island','◉',tr('Insel','Isla')],['words','▤',tr('Wörter','Palabras')],['shop','♛',tr('Shop','Tienda')],['profile','♙',tr('Profil','Perfil')]].map(([r,i,l])=>`<button class="${active===r?'active':''}" data-action="navigate" data-route="${r}"><span>${i}</span><small>${l}</small></button>`).join('')}</nav>`}
function progressCard(){const s=getState(),lv=levelFromXp(s.progress.xp),p=levelProgress(s.progress.xp);return `<section class="progress-card"><div class="progress-head"><strong>${tr('Level','Nivel')} ${lv}</strong><span>${tr(`Noch ${p.missing} XP bis Level ${lv+1}`,`Faltan ${p.missing} XP para nivel ${lv+1}`)}</span></div><div class="bar"><i style="width:${p.percent}%"></i></div></section>`}
function renderComplete(title,reward,back='world'){return `<div class="v3-shell page">${top()}<section class="celebration"><img src="assets/illustrations/tula-welcome.svg" alt="Tula"><span class="eyebrow">${tr('ABENTEUER GESCHAFFT','AVENTURA COMPLETADA')}</span><h1>${title}</h1><div class="reward-row"><div>✨<strong>+${reward.xp}</strong><small>XP</small></div><div>🐚<strong>+${reward.shells}</strong><small>${tr('Muscheln','Conchas')}</small></div></div><button class="primary" data-action="navigate" data-route="home">⌂ ${tr('Zur Startseite','Ir al inicio')}</button><button class="secondary" data-action="navigate" data-route="${back}">${tr('Weitere Übung','Otro ejercicio')}</button></section></div>`}

router.register('home',()=>{const s=getState();return `<div class="v3-shell page">${top()}<section class="hero-v3"><div class="hero-copy"><span class="eyebrow">TURTLE ISLAND</span><h1>${tr('Komm mit auf die Insel!','¡Ven a la isla!')}</h1><p>${tr('Tula wartet auf dein nächstes Sprachabenteuer.','Tula espera tu próxima aventura lingüística.')}</p><button class="chip" data-action="navigate" data-route="island">${tr('Insel entdecken','Descubrir la isla')} →</button></div><img class="tula-art" src="assets/illustrations/tula-welcome.svg" alt="Tula"></section><section class="stats-v3"><div>✨<strong>${s.progress.xp}</strong><small>XP</small></div><div>🐚<strong>${s.progress.shells}</strong><small>${tr('Muscheln','Conchas')}</small></div><div>🔥<strong>${s.progress.streak}</strong><small>${tr('Lerntage','Días')}</small></div></section>${progressCard()}<section class="journey-grid">${collections.map(c=>`<button data-action="open-world" data-collection="${c.id}"><span>${c.icon}</span><div><strong>${c[s.language]}</strong><small>${s.progress.learned[c.id]||0}/${c.words.length} ${tr('Wörter entdeckt','palabras descubiertas')}</small></div><b>→</b></button>`).join('')}<button data-action="start-adaptive"><span>🧠</span><div><strong>${tr('Schlaue Wiederholung','Repaso inteligente')}</strong><small>${tr('Persönlicher Wortmix','Mezcla personal')}</small></div><b>→</b></button><button data-action="navigate" data-route="speaking"><span>🎙️</span><div><strong>${tr('Sprechtrainer','Entrenador de voz')}</strong><small>${tr('Anhören und nachsprechen','Escuchar y repetir')}</small></div><b>→</b></button><button data-action="navigate" data-route="stories"><span>📖</span><div><strong>${tr('Mini-Geschichten','Mini historias')}</strong><small>${tr('Lesen, hören, verstehen','Leer, escuchar, comprender')}</small></div><b>→</b></button></section></div>${nav('home')}`});
router.register('island',()=>{const s=getState();return `<div class="v3-shell page">${top()}<section class="page-title"><span class="eyebrow">TURTLE ISLAND</span><h1>${tr('Wohin möchtest du?','¿Adónde quieres ir?')}</h1></section><button class="island-card"><img src="assets/illustrations/turtle-island.svg" alt="Turtle Island"></button><section class="places island-place-grid">${collections.map((c,i)=>`<button class="place" data-action="open-world" data-collection="${c.id}"><span>${c.icon}</span><strong>${c[s.language]}</strong><small>${c[s.language==='de'?'subtitleDe':'subtitleEs']}</small><span class="place-number">${String(i+1).padStart(2,'0')}</span></button>`).join('')}<button class="place" data-action="navigate" data-route="tula-home"><span>🏡</span><strong>${tr('Tulas Zuhause','Casa de Tula')}</strong><small>${tr('Einrichten & verkleiden','Decorar y vestir')}</small></button><button class="place" data-action="open-harbor"><span>⚓</span><strong>${tr('Hafen','Puerto')}</strong><small>${tr('Ab Level 7','Desde nivel 7')}</small></button><button class="place" data-action="open-castle"><span>🏰</span><strong>${tr('Schloss','Castillo')}</strong><small>${tr('Ab Level 10','Desde nivel 10')}</small></button></section></div>${nav('island')}`});
router.register('world',()=>{const s=getState(),c=currentCollection(),unlocked=s.inventory.unlockedModes;return `<div class="v3-shell page">${top('island')}<section class="place-hero"><span>${c.icon}</span><div><span class="eyebrow">${tr('LERNWELT','MUNDO DE APRENDIZAJE')}</span><h1>${c[s.language]}</h1><p>${c[s.language==='de'?'subtitleDe':'subtitleEs']}</p></div></section><section class="world-instruction"><span class="world-step">1</span><div><strong>${tr('Wähle jetzt eine Übung','Elige ahora un ejercicio')}</strong><small>${tr('Jede Übung öffnet einen eigenen Bildschirm.','Cada ejercicio abre su propia pantalla.')}</small></div></section><section class="mode-picker"><button data-action="navigate" data-route="explore"><span>👀</span><div><strong>${tr('Wörter entdecken','Descubrir palabras')}</strong></div><b>→</b></button><button data-action="navigate" data-route="listening"><span>🎧</span><div><strong>${tr('Hör-Abenteuer','Aventura auditiva')}</strong></div><b>→</b></button><button data-action="navigate" data-route="sentence"><span>✒️</span><div><strong>${tr('Satzwerkstatt','Taller de frases')}</strong></div><b>→</b></button><button data-action="${unlocked.includes('memory')?'start-memory':'navigate'}" ${unlocked.includes('memory')?'':'data-route="shop"'}><span>🏛️</span><div><strong>${tr('Palast-Memory','Memoria del palacio')}</strong></div><b>${unlocked.includes('memory')?'→':'🔒'}</b></button><button data-action="${unlocked.includes('speed')?'start-speed':'navigate'}" ${unlocked.includes('speed')?'':'data-route="shop"'}><span>⏱️</span><div><strong>${tr('Goldene Minute','Minuto dorado')}</strong></div><b>${unlocked.includes('speed')?'→':'🔒'}</b></button></section></div>${nav(c.id==='library'?'words':'island')}`});
router.register('words',()=>{setState(d=>{d.session.collectionId='library';d.route={name:'world',params:{}};return d});return router.navigate('world',{},{persist:false})});
router.register('shop',()=>renderShop({top,nav}));
router.register('profile',()=>renderProfile({top,nav,progressCard}));
router.register('settings',()=>renderSettings({top,nav}));
router.register('child-profile',()=>renderChildProfile({top,nav}));
registerLearningRoutes(router,{top,nav,progressCard,renderComplete,currentCollection,tr});
registerAdvancedRoutes(router,{top,nav,renderComplete});
registerExperienceRoutes(router,{top,nav});
router.setNotFound(()=>`<div class="v3-shell page">${top('home')}<section class="page-title"><h1>${tr('Seite nicht gefunden','Página no encontrada')}</h1></section></div>`);
registerAction('navigate',({data})=>router.navigate(data.route));
registerAction('open-world',({data})=>{setState(d=>{d.session.collectionId=data.collection;return d});router.navigate('world')});
registerAction('toggle-language',()=>{setState(d=>{d.language=d.language==='de'?'es':'de';return d});router.renderCurrent()});
registerAction('menu',()=>router.navigate('settings'));
registerLearningActions(router,{renderComplete,currentCollection,tr});
registerAdvancedActions(router,{renderComplete});
registerProgressionActions(router);
registerChildProfileActions(router);
registerExperienceActions(router);
bindActions(app);
router.renderCurrent();
