export const EN_UI = {
  'Home':'Home','Insel':'Island','Wörter':'Words','Shop':'Shop','Profil':'Profile','Level':'Level','Muscheln':'Shells','Lerntage':'Learning days',
  'SPRACHEN':'LANGUAGES','Welche Sprache möchtest du lernen?':'Which language would you like to learn?','Wähle zuerst deine Sprache und danach die Lernsprache.':'First choose your language, then the language you want to learn.','VON':'FROM','NACH':'TO','Meine Sprache':'My language','Ich lerne':'I am learning','Sprachreise starten':'Start language journey','Sprachen tauschen':'Swap languages',
  'Komm mit auf die Insel!':'Come to the island!','Tula wartet auf dein nächstes Sprachabenteuer.':'Tula is waiting for your next language adventure.','Insel entdecken':'Explore the island','Wörter entdeckt':'words discovered','Schlaue Wiederholung':'Smart review','Persönliche Übungsrunde':'Personal practice round','Sprechtrainer':'Speaking trainer','Anhören und nachsprechen':'Listen and repeat','Mini-Geschichten':'Mini stories','Lesen, hören und entdecken':'Read, listen and explore',
  'Wohin möchtest du?':'Where would you like to go?','Tulas Zuhause':'Tula’s Home','Einrichten & dekorieren':'Decorate and furnish','Hafen':'Harbor','Reise & Dialoge':'Travel and dialogues','Ab Level 7':'From level 7','Schloss':'Castle','Goldene Sprachprüfung':'Golden language challenge','Ab Level 10':'From level 10',
  'LERNWELT':'LEARNING WORLD','Wähle jetzt eine Übung':'Choose an exercise','Wörter entdecken':'Discover words','Ansehen, hören und merken':'Look, listen and remember','Hör-Abenteuer':'Listening adventure','Hören und auswählen':'Listen and choose','Satzwerkstatt':'Sentence workshop','Sätze in Reihenfolge bringen':'Put sentences in order','Palast-Memory':'Palace Memory','Goldene Minute':'Golden Minute',
  'ABENTEUER GESCHAFFT':'ADVENTURE COMPLETE','Tula ist stolz auf dich.':'Tula is proud of you.','Zur Startseite':'Back to home','Weitere Übung':'Another exercise','WÖRTER ENTDECKEN':'DISCOVER WORDS','Tippe eine Karte an, um das Wort zu hören.':'Tap a card to hear the word.','Lernrunde abschließen · 🐚 6':'Finish learning round · 🐚 6','Hör-Abenteuer geschafft!':'Listening adventure complete!','Hör gut zu':'Listen carefully','Welches Bild gehört zum Wort?':'Which picture matches the word?','Noch einmal':'Again','SATZWERKSTATT':'SENTENCE WORKSHOP','Baue den Satz':'Build the sentence','Tippe die Wörter in der richtigen Reihenfolge an.':'Tap the words in the correct order.','DEINE VORLAGE':'YOUR EXAMPLE','Baue deinen Satz hier':'Build your sentence here','Tippe unten auf die Wortkarten.':'Tap the word cards below.','Neu mischen':'Shuffle again','Satz prüfen':'Check sentence','Wörter entdeckt!':'Words discovered!','Satzwerkstatt geschafft!':'Sentence workshop complete!',
  'DEIN FORTSCHRITT':'YOUR PROGRESS','ELTERNBEREICH':'PARENT AREA','Einstellungen':'Settings','Kinderprofil':'Child profile','Name':'Name','Altersstufe':'Age group','Lernziel':'Learning goal','Unterstützung':'Support','Speichern':'Save','Zurück':'Back','Audio':'Audio','Animationen':'Animations','Musik':'Music','An':'On','Aus':'Off',
  'Muschel-Boutique':'Shell Boutique','Freischalten':'Unlock','Gekauft':'Purchased','Nicht genug Muscheln':'Not enough shells','Meilensteine':'Milestones','Belohnung abholen':'Claim reward','Abgeholt':'Claimed','Tulas Zuhause gestalten':'Decorate Tula’s home','Kaufen':'Buy',
  'Finde die Paare':'Find the pairs','Zeit':'Time','Punkte':'Points','Richtig':'Correct','Weiter':'Continue','Nochmal spielen':'Play again','Geschafft!':'Complete!','Start':'Start','Stopp':'Stop','Schließen':'Close','Öffnen':'Open','Heute':'Today','Tage':'Days','Wiederholen':'Review',
  'Noch':'Only','bis Level':'to level','Noch {missing} XP bis Level {level}':'{missing} XP to level {level}'
};

export const englishUi = german => EN_UI[german] || german;
