export const EN_UI = {
  'Home':'Home','Insel':'Island','Wörter':'Words','Shop':'Shop','Profil':'Profile','Level':'Level','Muscheln':'Shells','Lerntage':'Learning days',
  'SPRACHEN':'LANGUAGES','Welche Sprache möchtest du lernen?':'Which language would you like to learn?','Wähle zuerst deine Sprache und danach die Lernsprache.':'First choose your language, then the language you want to learn.','VON':'FROM','NACH':'TO','Meine Sprache':'My language','Ich lerne':'I am learning','Sprachreise starten':'Start language journey','Sprachen tauschen':'Swap languages',
  'Komm mit auf die Insel!':'Come to the island!','Tula wartet auf dein nächstes Sprachabenteuer.':'Tula is waiting for your next language adventure.','Insel entdecken':'Explore the island','Wörter entdeckt':'words discovered','Schlaue Wiederholung':'Smart review','Persönliche Übungsrunde':'Personal practice round','Sprechtrainer':'Speaking trainer','Anhören und nachsprechen':'Listen and repeat','Mini-Geschichten':'Mini stories','Lesen, hören und entdecken':'Read, listen and explore',
  'Wohin möchtest du?':'Where would you like to go?','Tippe einen Ort auf der Karte an.':'Tap a place on the map.','Interaktive Inselkarte':'Interactive island map','Tulas Zuhause':'Tula’s Home','Einrichten & dekorieren':'Decorate and furnish','Hafen':'Harbor','Reise & Dialoge':'Travel and dialogues','Ab Level':'From level','Ab Level 7':'From level 7','Schloss':'Castle','Goldene Sprachprüfung':'Golden language challenge','Ab Level 10':'From level 10','Freigeschaltet ab Level':'Available from level','Diese Lernwelt öffnet':'This learning world opens',
  'LERNWELT':'LEARNING WORLD','Wähle jetzt eine Übung':'Choose an exercise','Wörter entdecken':'Discover words','Ansehen, hören und merken':'Look, listen and remember','Hör-Abenteuer':'Listening adventure','Hören und auswählen':'Listen and choose','Satzwerkstatt':'Sentence workshop','Sätze in Reihenfolge bringen':'Put sentences in order','Palast-Memory':'Palace Memory','Goldene Minute':'Golden Minute','Bild und Wort verbinden':'Match picture and word','In der Boutique freischalten':'Unlock in the boutique','45 Sekunden Sprachtempo':'45 seconds of language speed',
  'ABENTEUER GESCHAFFT':'ADVENTURE COMPLETE','Tula ist stolz auf dich.':'Tula is proud of you.','Zur Startseite':'Back to home','Weitere Übung':'Another exercise','WÖRTER ENTDECKEN':'DISCOVER WORDS','Tippe eine Karte an, um das Wort zu hören.':'Tap a card to hear the word.','Lernrunde abschließen':'Finish learning round','Hör-Abenteuer geschafft!':'Listening adventure complete!','Hör gut zu':'Listen carefully','Welches Bild gehört zum Wort?':'Which picture matches the word?','Noch einmal':'Again','SATZWERKSTATT':'SENTENCE WORKSHOP','Baue den Satz':'Build the sentence','Tippe die Wörter in der richtigen Reihenfolge an.':'Tap the words in the correct order.','DEINE VORLAGE':'YOUR EXAMPLE','Baue deinen Satz hier':'Build your sentence here','Tippe unten auf die Wortkarten.':'Tap the word cards below.','Neu mischen':'Shuffle again','Satz prüfen':'Check sentence','Wörter entdeckt!':'Words discovered!','Satzwerkstatt geschafft!':'Sentence workshop complete!',
  'Neue Wörter lernen':'Learn new words','Wähle eine Wortwelt. Neue Wörter kannst du mit deinen Muscheln freischalten.':'Choose a word world. Unlock new words with your shells.','Muscheln verfügbar':'shells available','Wörter bereit':'words ready','Wortwelten':'Word worlds','Jetzt üben':'Practice now','Wort anhören':'Listen to word','Startwort':'Starter word','Bereit zum Lernen':'Ready to learn','Du brauchst mehr Muscheln.':'You need more shells.','Wort freigeschaltet!':'Word unlocked!','Tippe eine Karte an, um das Wort zu hören. Neue Wörter findest du im Wörter-Bereich.':'Tap a card to hear the word. Find more words in the Words area.',
  'PALAST-MEMORY':'PALACE MEMORY','Palast-Memory geschafft!':'Palace Memory complete!','Finde die Paare':'Find the pairs','Verbinde Bild und passendes Wort.':'Match each picture with the correct word.','ZEIT-ABENTEUER':'TIME ADVENTURE','Übersetze so viele Wörter wie möglich.':'Translate as many words as you can.','ZEIT':'TIME','PUNKTE':'POINTS','ÜBERSETZE':'TRANSLATE','Goldene Minute beendet!':'Golden Minute complete!',
  'MUSCHEL-BOUTIQUE':'SHELL BOUTIQUE','Besondere Schätze':'Special treasures','Alles wird erspielt – keine echten Käufe.':'Everything is earned through play – no real purchases.','verfügbare Muscheln':'available shells','Neuen Spielmodus freischalten':'Unlock a new game mode','Für kommende Aufgaben':'For upcoming activities','Vorrat':'Inventory',
  'DEIN FORTSCHRITT':'YOUR PROGRESS','Inselentdecker':'Island Explorer','Kinderprofil anpassen':'Edit child profile','Sprachpaar ändern':'Change language pair','entdeckt':'discovered','LEVEL-BELOHNUNGEN':'LEVEL REWARDS','Deine nächsten Schätze':'Your next treasures','Meilenstein-Belohnung':'Milestone reward','Abholen':'Claim','Eltern & Einstellungen':'Parents & settings',
  'ELTERNBEREICH':'PARENT AREA','Lernumgebung':'Learning environment','Tagesziel':'Daily goal','Audio und Sprache':'Audio and speech','Animationen':'Animations','Elternhinweis':'Note for parents','Der Fortschritt wird lokal gespeichert. Es gibt aktuell keine echten Käufe.':'Progress is stored locally. There are currently no real purchases.','Testfortschritt zurücksetzen':'Reset test progress','Fortschritt wirklich zurücksetzen?':'Do you really want to reset progress?',
  'KINDERPROFIL':'CHILD PROFILE','Lernen passend zum Kind':'Learning tailored to the child','Name oder Spitzname':'Name or nickname','Alters- und Lernstufe':'Age and learning stage','Antworten':'answers','Lernziel':'Learning goal','Sprechen':'Speaking','Gemischt':'Balanced','Lesen':'Reading','Hilfestufe':'Support level','Viel Hilfe':'Lots of help','Normal':'Normal','Mehr Herausforderung':'More challenge','Antwortmöglichkeiten':'answer choices','Wörter pro Satz':'words per sentence','Profil speichern':'Save profile',
  'Wiederholung geschafft!':'Review complete!','SPRECHTRAINER':'SPEAKING TRAINER','Sprich mit Tula':'Speak with Tula','Höre ein Wort und sprich es laut nach.':'Listen to a word and say it aloud.','Anhören & nachsprechen':'Listen & repeat','MINI-GESCHICHTEN':'MINI STORIES','Tulas Geschichten':'Tula’s stories','Kapitel':'chapters','Geschichte geschafft!':'Story complete!','Weitere Geschichte':'Another story','Vorlesen':'Read aloud','Weiter':'Continue','Abenteuer geschafft!':'Adventure complete!','Zur Insel':'Back to the island','BOSS-LEVEL':'BOSS LEVEL','REISE & DIALOGE':'TRAVEL & DIALOGUES','TULAS ZUHAUSE':'TULA’S HOME','Mach es dir gemütlich':'Make yourself at home','Gekauft':'Purchased','Aufstellen':'Place','Kaufen':'Buy','Ziehen & abstellen':'Drag and place','Die Positionen bleiben gespeichert':'Positions stay saved','Aufräumen':'Tidy up','Aufgestellt':'Placed','Im Inventar':'In inventory','Anziehen':'Put on','Ausziehen':'Take off','Tula trägt es':'Tula is wearing it','Tula trägt':'Tula is wearing','Wähle ein Outfit für Tula':'Choose an outfit for Tula','verschieben':'move',
  'Einstellungen':'Settings','Kinderprofil':'Child profile','Name':'Name','Altersstufe':'Age group','Unterstützung':'Support','Speichern':'Save','Zurück':'Back','Audio':'Audio','Musik':'Music','An':'On','Aus':'Off',
  'Muschel-Boutique':'Shell Boutique','Freischalten':'Unlock','Nicht genug Muscheln':'Not enough shells','Meilensteine':'Milestones','Belohnung abholen':'Claim reward','Abgeholt':'Claimed','Tulas Zuhause gestalten':'Decorate Tula’s home',
  'Zeit':'Time','Punkte':'Points','Richtig':'Correct','Nochmal spielen':'Play again','Geschafft!':'Complete!','Start':'Start','Stopp':'Stop','Schließen':'Close','Öffnen':'Open','Heute':'Today','Tage':'Days','Wiederholen':'Review','Seite nicht gefunden':'Page not found'
};

export const englishUi = german => EN_UI[german] || german;
