import {
  getState, setState, registerAction, spendShells, levelFromXp, resetState,
  sourceLanguage, languageValue, uiText
} from '../core/index.js';
import { assets } from '../../config/assets.js';

const shopItems=[
{id:'sentence',type:'mode',icon:'✒️',cost:80,de:'Satzwerkstatt',es:'Taller de frases',el:'Εργαστήριο προτάσεων'},
{id:'memory',type:'mode',icon:'🏛️',cost:120,de:'Palast-Memory',es:'Memoria del palacio',el:'Μνήμη του παλατιού'},
{id:'speed',type:'mode',icon:'⏱️',cost:160,de:'Goldene Minute',es:'Minuto dorado',el:'Χρυσό λεπτό'},
{id:'doubleXp',type:'booster',icon:'⚡',cost:60,de:'Doppel-XP',es:'XP doble',el:'Διπλά XP'},
{id:'hints',type:'booster',icon:'💡',cost:25,de:'Hinweis',es:'Pista',el:'Υπόδειξη'},
{id:'jumps',type:'booster',icon:'🚀',cost:35,de:'Startsprung',es:'Salto inicial',el:'Αρχικό άλμα'}
];
const milestones=[3,5,7,10,15,20,30];
const tr=(de,es,el=de)=>uiText(de,es,el);

export function renderShop({top,nav}){const s=getState(),source=sourceLanguage();return `<div class="v3-shell page">${top()}<section class="shop-hero-v3"><span>♛</span><div><span class="eyebrow">${tr('MUSCHEL-BOUTIQUE','BOUTIQUE DE CONCHAS','ΚΑΤΑΣΤΗΜΑ ΚΟΧΥΛΙΩΝ')}</span><h1>${tr('Besondere Schätze','Tesoros especiales','Ξεχωριστοί θησαυροί')}</h1><p>${tr('Alles wird erspielt – keine echten Käufe.','Todo se gana jugando; no hay compras reales.','Όλα κερδίζονται παίζοντας – χωρίς πραγματικές αγορές.')}</p></div></section><section class="wallet-card"><span>🐚</span><div><strong>${s.progress.shells}</strong><small>${tr('verfügbare Muscheln','conchas disponibles','διαθέσιμα κοχύλια')}</small></div></section><section class="shop-section">${shopItems.map(item=>{const owned=item.type==='mode'&&s.inventory.unlockedModes.includes(item.id);const count=item.type==='booster'?s.inventory.boosters[item.id]||0:0;return `<article class="shop-card-v3 ${owned?'owned':''}"><span>${item.icon}</span><div><strong>${languageValue(item,source)}</strong><small>${item.type==='mode'?tr('Neuen Spielmodus freischalten','Desbloquear un modo nuevo','Ξεκλείδωσε νέο παιχνίδι'):tr('Für kommende Aufgaben','Para próximas tareas','Για επόμενες ασκήσεις')}</small>${count?`<em>${tr('Vorrat','Inventario','Απόθεμα')}: ${count}</em>`:''}</div><button data-action="buy-item" data-item="${item.id}" ${owned?'disabled':''}>${owned?'✓':`🐚 ${item.cost}`}</button></article>`}).join('')}</section></div>${nav('shop')}`}

export function renderProfile({top,nav,progressCard}){const s=getState(),lv=levelFromXp(s.progress.xp);return `<div class="v3-shell page">${top()}<section class="profile-hero-v3"><img src="${assets.characters.tula.poses.profile}" alt="Tula"><span class="eyebrow">${tr('DEIN FORTSCHRITT','TU PROGRESO','Η ΠΡΟΟΔΟΣ ΣΟΥ')}</span><h1>${s.profile.name||tr('Inselentdecker','Explorador','Εξερευνητής')}</h1><strong>${tr('Level','Nivel','Επίπεδο')} ${lv} · ${s.progress.xp} XP</strong><button class="profile-settings-link" data-action="navigate" data-route="child-profile">${tr('Kinderprofil anpassen','Ajustar perfil infantil','Ρύθμιση παιδικού προφίλ')}</button><button class="profile-settings-link" data-action="navigate" data-route="language-select">🌍 ${tr('Sprachpaar ändern','Cambiar idiomas','Αλλαγή γλωσσών')}</button></section>${progressCard()}<section class="profile-stats"><div><span>🔥</span><strong>${s.progress.streak}</strong><small>${tr('Lerntage','Días','Ημέρες')}</small></div><div><span>🐚</span><strong>${s.progress.shells}</strong><small>${tr('Muscheln','Conchas','Κοχύλια')}</small></div><div><span>📚</span><strong>${Object.values(s.progress.learned).reduce((a,b)=>a+Number(b||0),0)}</strong><small>${tr('entdeckt','descubiertas','ανακαλύφθηκαν')}</small></div></section><section class="milestone-list"><div class="section-head"><div><span class="eyebrow">${tr('LEVEL-BELOHNUNGEN','RECOMPENSAS','ΑΝΤΑΜΟΙΒΕΣ')}</span><h2>${tr('Deine nächsten Schätze','Tus próximos tesoros','Οι επόμενοι θησαυροί σου')}</h2></div></div>${milestones.map(level=>{const reached=lv>=level,claimed=s.inventory.claimedMilestones.includes(level);return `<article class="milestone-card ${reached?'reached':''}"><span>${level>=20?'👑':level>=10?'🚀':'🐚'}</span><div><small>LEVEL ${level}</small><strong>${tr('Meilenstein-Belohnung','Recompensa de nivel','Ανταμοιβή επιπέδου')}</strong><em>+${level*10} 🐚</em></div>${claimed?'<b>✓</b>':reached?`<button data-action="claim-milestone" data-level="${level}">${tr('Abholen','Recoger','Παραλαβή')}</button>`:'<b>🔒</b>'}</article>`}).join('')}</section><button class="secondary" data-action="open-settings">⚙️ ${tr('Eltern & Einstellungen','Padres y ajustes','Γονείς και ρυθμίσεις')}</button></div>${nav('profile')}`}

export function renderSettings({top,nav}){const s=getState();return `<div class="v3-shell page">${top('profile')}<section class="page-title"><span class="eyebrow">${tr('ELTERNBEREICH','ZONA DE PADRES','ΠΕΡΙΟΧΗ ΓΟΝΕΩΝ')}</span><h1>${tr('Lernumgebung','Entorno de aprendizaje','Περιβάλλον μάθησης')}</h1></section><section class="parent-summary"><div><strong>${levelFromXp(s.progress.xp)}</strong><small>${tr('Level','Nivel','Επίπεδο')}</small></div><div><strong>${s.progress.xp}</strong><small>XP</small></div><div><strong>${s.progress.daily}/5</strong><small>${tr('Tagesziel','Meta diaria','Ημερήσιος στόχος')}</small></div></section><label class="setting-row"><span>🔊 <b>${tr('Audio und Sprache','Audio y voz','Ήχος και φωνή')}</b></span><input type="checkbox" data-action="toggle-setting" data-setting="sound" ${s.settings.sound?'checked':''}></label><label class="setting-row"><span>✨ <b>${tr('Animationen','Animaciones','Κινήσεις')}</b></span><input type="checkbox" data-action="toggle-setting" data-setting="motion" ${s.settings.motion?'checked':''}></label><section class="parent-note"><strong>${tr('Elternhinweis','Nota para padres','Σημείωση για γονείς')}</strong><p>${tr('Der Fortschritt wird lokal gespeichert. Es gibt aktuell keine echten Käufe.','El progreso se guarda localmente. No hay compras reales.','Η πρόοδος αποθηκεύεται τοπικά. Δεν υπάρχουν πραγματικές αγορές.')}</p></section><button class="danger-soft" data-action="reset-progress">${tr('Testfortschritt zurücksetzen','Restablecer progreso','Επαναφορά προόδου')}</button></div>${nav('profile')}`}

export function registerProgressionActions(router){
 registerAction('buy-item',({data})=>{const item=shopItems.find(x=>x.id===data.item);if(!item||!spendShells(item.cost))return;if(item.type==='mode')setState(d=>{if(!d.inventory.unlockedModes.includes(item.id))d.inventory.unlockedModes.push(item.id);return d});else setState(d=>{d.inventory.boosters[item.id]=(d.inventory.boosters[item.id]||0)+1;return d});router.renderCurrent()});
 registerAction('claim-milestone',({data})=>{const level=Number(data.level),s=getState();if(levelFromXp(s.progress.xp)<level||s.inventory.claimedMilestones.includes(level))return;setState(d=>{d.inventory.claimedMilestones.push(level);d.progress.shells+=level*10;return d});router.renderCurrent()});
 registerAction('open-settings',()=>router.navigate('settings'));
 registerAction('toggle-setting',({target,data})=>{setState(d=>{d.settings[data.setting]=Boolean(target.checked);return d})});
 registerAction('reset-progress',()=>{if(confirm(tr('Fortschritt wirklich zurücksetzen?','¿Restablecer el progreso?','Θέλεις πραγματικά να επαναφέρεις την πρόοδο;'))){resetState();router.navigate('home')}});
}
