import {collections} from './content.js';
const app=document.querySelector('#app');
const KEY='linguaturtle-v3-preview-local';
let state={lang:'de',xp:245,shells:182,screen:'home',collection:'garden',...JSON.parse(localStorage.getItem(KEY)||'{}')};
const t=(de,es)=>state.lang==='de'?de:es;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function header(){return `<header><button data-home>🐢</button><strong>LinguaTurtle</strong><button data-lang>${state.lang==='de'?'🇩🇪 DE':'🇪🇸 ES'}</button><span>🐚 ${state.shells}</span></header>`}
function home(){app.innerHTML=`<main>${header()}<section class="hero"><div><small>TURTLE ISLAND</small><h1>${t('Komm mit auf die Insel!','¡Ven a la isla!')}</h1><p>${t('Wähle eine Lernwelt und starte dein Sprachabenteuer.','Elige un mundo y comienza tu aventura lingüística.')}</p></div><div class="tula">🐢</div></section><section class="stats"><div><b>${state.xp}</b><span>XP</span></div><div><b>${Math.floor(state.xp/100)+1}</b><span>${t('Level','Nivel')}</span></div><div><b>${state.shells}</b><span>${t('Muscheln','Conchas')}</span></div></section><h2>${t('Deine Lernwelten','Tus mundos')}</h2><section class="worlds">${collections.map(c=>`<button data-world="${c.id}"><span>${c.icon}</span><div><b>${c[state.lang]}</b><small>${c[state.lang==='de'?'subtitleDe':'subtitleEs']}</small></div><i>→</i></button>`).join('')}</section></main>`;bind()}
function world(){const c=collections.find(x=>x.id===state.collection)||collections[0];app.innerHTML=`<main>${header()}<button class="back" data-home>← ${t('Zurück','Atrás')}</button><section class="worldHero"><span>${c.icon}</span><div><small>${t('LERNWELT','MUNDO')}</small><h1>${c[state.lang]}</h1><p>${c[state.lang==='de'?'subtitleDe':'subtitleEs']}</p></div></section><h2>${t('Wörter entdecken','Descubrir palabras')}</h2><section class="cards">${c.words.map(w=>`<button data-word="${w.id}"><span>${w.emoji}</span><b>${w[state.lang]}</b><small>${w[state.lang==='de'?'es':'de']}</small></button>`).join('')}</section></main>`;bind()}
function bind(){document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>{state.screen='home';save();home()});document.querySelector('[data-lang]')?.addEventListener('click',()=>{state.lang=state.lang==='de'?'es':'de';save();state.screen==='home'?home():world()});document.querySelectorAll('[data-world]').forEach(x=>x.onclick=()=>{state.collection=x.dataset.world;state.screen='world';save();world()});document.querySelectorAll('[data-word]').forEach(x=>x.onclick=()=>{const c=collections.find(y=>y.id===state.collection);const w=c.words.find(y=>y.id===x.dataset.word);if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w[state.lang==='de'?'es':'de']);u.lang=state.lang==='de'?'es-ES':'de-DE';u.rate=.8;speechSynthesis.speak(u)}state.xp+=2;state.shells+=1;save();x.classList.add('learned')})}
state.screen==='world'?world():home();